import { GameAction, Location, Storyline, Relationship, RandomEvent, NaturgemaldeNode } from './types';

// ===== LOCATIONS =====
export const initialLocations: Record<string, Location> = {
  berlin: {
    id: 'berlin', name: 'Berlin, Prussia', region: 'Europe',
    description: 'The grand capital. Salons buzz with Enlightenment discourse. Your mother has passed, leaving you free to pursue your dream.',
    atmosphere: 'Candlelit libraries. The weight of possibility.',
    actions: ['berlin_prepare', 'berlin_saloon', 'berlin_study', 'berlin_rest', 'berlin_instruments', 'berlin_goethe'],
    connections: [],
    discovered: true,
  },
  cumana: {
    id: 'cumana', name: 'Cumaná, New Andalusia', region: 'South America · 1799',
    description: 'You have just landed on the Caribbean coast of the Spanish colony of New Andalusia. The heat is extraordinary. A mountain rises behind the cacao groves; the town carries the wounds of the 1797 earthquake. Your expedition begins here, among people who already know this land.',
    atmosphere: 'Salt and wet timber. A sharp white light. Leaves that do not fit a European field guide.',
    actions: ['cumana_temperature', 'cumana_bonpland', 'cumana_listen', 'cumana_specimen', 'cumana_rest'],
    connections: ['caracas'],
    discovered: false,
  },
  caracas: {
    id: 'caracas', name: 'Caracas, Venezuela', region: 'South America',
    description: 'The warm Caribbean air greets you. The Captaincy General of Venezuela stretches before you — a land of dramatic contrasts.',
    atmosphere: 'Tropical heat. Colonial architecture. Unfamiliar flowers.',
    actions: ['caracas_explore', 'caracas_bonpland', 'caracas_market', 'caracas_rest', 'caracas_collect', 'caracas_humboldt_current'],
    connections: ['cumana', 'llanos', 'lake_valencia', 'cuba'],
    discovered: false,
  },
  cuba: {
    id: 'cuba', name: 'Cuba', region: 'Caribbean',
    description: 'The pearl of the Antilles. A Spanish colony of immense strategic importance, where you can observe both the beauty and brutality of colonial rule.',
    atmosphere: 'Sugar plantations. Enslaved laborers. The tension between nature and exploitation.',
    actions: ['cuba_explore', 'cuba_slavery', 'cuba_collect', 'cuba_rest', 'cuba_magnetic'],
    connections: ['caracas', 'mexico'],
    discovered: false,
  },
  llanos: {
    id: 'llanos', name: 'The Venezuelan Llanos', region: 'South America',
    description: 'Vast, treeless plains extend to the horizon. Home to wild horses, capybaras, and the llaneros.',
    atmosphere: 'Endless grass. Blazing sun. Thunder of hooves.',
    actions: ['llanos_explore', 'llanos_survive', 'llanos_llanero', 'llanos_hunt', 'llanos_observe'],
    connections: ['caracas', 'orinoco'],
    discovered: false,
  },
  lake_valencia: {
    id: 'lake_valencia', name: 'Lake Valencia', region: 'South America',
    description: 'Once a great body of water, the lake has been receding alarmingly. Forests cleared upstream.',
    atmosphere: 'Shallow waters. Exposed mudflats. Stumps of felled trees.',
    actions: ['valencia_measure', 'valencia_investigate', 'valencia_farmer', 'valencia_sketch', 'valencia_rest'],
    connections: ['caracas', 'llanos'],
    discovered: false,
  },
  orinoco: {
    id: 'orinoco', name: 'The Orinoco River', region: 'South America',
    description: 'The great river winds through dense jungle. Its waters teem with life — and danger.',
    atmosphere: 'Dark waters. Jungle cacophony. Humidity that clings.',
    actions: ['orinoco_navigate', 'orinoco_eels', 'orinoco_indigenous', 'orinoco_collect', 'orinoco_rest'],
    connections: ['llanos', 'andes_foothills'],
    discovered: false,
  },
  andes_foothills: {
    id: 'andes_foothills', name: 'Andes Foothills', region: 'South America',
    description: 'The great mountain chain rises before you. Vegetation changes dramatically with altitude.',
    atmosphere: 'Cool mountain air. Changing ecosystems. Call of condors.',
    actions: ['andes_climb', 'andes_measure', 'andes_observe', 'andes_guide', 'andes_rest'],
    connections: ['orinoco', 'chimborazo'],
    discovered: false,
  },
  chimborazo: {
    id: 'chimborazo', name: 'Chimborazo, Ecuador', region: 'South America',
    description: 'The great volcano towers above all. At 19,286 feet, believed to be the highest peak in the world.',
    atmosphere: 'Crystalline air. Vertiginous heights. The curve of the Earth.',
    actions: ['chimborazo_ascent', 'chimborazo_measure', 'chimborazo_naturgemalde', 'chimborazo_survive', 'chimborazo_rest'],
    connections: ['andes_foothills', 'mexico'],
    requiredFlag: 'reached_andes',
    discovered: false,
  },
  mexico: {
    id: 'mexico', name: 'New Spain (Mexico)', region: 'North America',
    description: 'A land of immense wealth and deep inequality. Silver mines pour riches into Spanish coffers.',
    atmosphere: 'Colonial grandeur. Silver and stone. Tension between worlds.',
    actions: ['mexico_survey', 'mexico_mine', 'mexico_political', 'mexico_rest', 'mexico_aztec'],
    connections: ['cuba', 'washington'],
    discovered: false,
  },
  washington: {
    id: 'washington', name: 'Washington D.C., USA', region: 'North America',
    description: 'The young American republic. You meet President Jefferson and share your discoveries about New Spain.',
    atmosphere: 'Political idealism. The tension between liberty and slavery. A nation in formation.',
    actions: ['washington_jefferson', 'washington_slavery', 'washington_data', 'washington_rest'],
    connections: ['mexico', 'paris'],
    discovered: false,
  },
  paris: {
    id: 'paris', name: 'Paris, France', region: 'Europe',
    description: 'You return to Europe after nearly five years. Now begins the great work of synthesis.',
    atmosphere: 'Scholarly intensity. The weight of accumulated knowledge.',
    actions: ['paris_write', 'paris_goethe', 'paris_lecture', 'paris_darwin', 'paris_kosmos', 'paris_publish'],
    connections: ['washington', 'berlin_later'],
    requiredFlag: 'returned_europe',
    discovered: false,
  },
  berlin_later: {
    id: 'berlin_later', name: 'Berlin (Later Years)', region: 'Europe',
    description: 'You return to Prussia as a celebrated scientist. The court expects your service, but your mind ranges across the cosmos.',
    atmosphere: 'Royal expectations. The weight of fame. A conservative court in a changing world.',
    actions: ['berlin_court', 'berlin_russia_prep', 'berlin_legacy', 'berlin_rest_later', 'berlin_1848'],
    connections: ['paris', 'russia'],
    requiredFlag: 'cosmos_started',
    discovered: false,
  },
  russia: {
    id: 'russia', name: 'The Russian Empire', region: 'Asia/Europe',
    description: 'At age 60, you embark on your final great expedition across the vast Russian Empire, from the Urals to the Altai Mountains.',
    atmosphere: 'Endless steppes. Extreme cold. The last great adventure of an aging explorer.',
    actions: ['russia_explore', 'russia_gold', 'russia_climate', 'russia_survive', 'russia_observe'],
    connections: ['berlin_later'],
    requiredFlag: 'russia_expedition',
    discovered: false,
  },
};

// ===== ACTIONS (Citizen Sleeper style - assigned dice) =====
export const allActions: Record<string, GameAction> = {
  // === BERLIN ===
  berlin_prepare: {
    id: 'berlin_prepare', name: 'Prepare for Expedition', location: 'berlin',
    description: 'Study maps, plan routes, and ready yourself for the journey ahead.',
    dieRequired: 1, skill: 'logic',
    effects: { resources: { data: 3 }, flag: 'expedition_ready', storyline: 'expedition_prep' },
    successText: 'Your preparations are meticulous. Every contingency considered, every route mapped. The New World awaits.',
    failText: 'The scope of preparation is overwhelming. You feel underready, but time presses.',
    available: true,
  },
  berlin_saloon: {
    id: 'berlin_saloon', name: 'Attend the Salon', location: 'berlin',
    description: 'Visit Henriette Herz\'s salon. Intellectual discourse and potential alliances.',
    dieRequired: 2, skill: 'empathy',
    effects: { resources: { credits: 5 }, relationship: { id: 'herz', change: 1 }, storyline: 'intellectual_network' },
    successText: 'Henriette welcomes you warmly. The conversation flows — Kant, nature, the possibilities of the New World. You leave with new contacts and renewed purpose.',
    failText: 'The salon is lively but you feel out of place. Still, you exchange pleasantries.',
    available: true,
  },
  berlin_study: {
    id: 'berlin_study', name: 'Study Natural Philosophy', location: 'berlin',
    description: 'Spend time in the library, reading the latest scientific works.',
    dieRequired: 3, skill: 'logic',
    effects: { resources: { data: 5 }, storyline: 'scientific_foundation' },
    successText: 'A breakthrough in your reading! You connect Blumenbach\'s theories on vegetation with your own observations. The foundations of your worldview crystallize.',
    failText: 'The texts are dense and your mind wanders. Some knowledge absorbed, but no breakthrough.',
    available: true,
  },
  berlin_rest: {
    id: 'berlin_rest', name: 'Rest & Reflect', location: 'berlin',
    description: 'Take time to recover your strength and center yourself.',
    dieRequired: 1,
    effects: { resources: { vitality: 8 } },
    successText: 'You sleep deeply and wake refreshed. The weight of your mother\'s passing lifts, if only slightly.',
    failText: 'Restless sleep. Dreams of mountains and jungles.',
    available: true,
  },
  berlin_instruments: {
    id: 'berlin_instruments', name: 'Calibrate Instruments', location: 'berlin',
    description: 'Test and calibrate your 42 scientific instruments before departure.',
    dieRequired: 4, skill: 'logic',
    cost: { credits: 10 },
    effects: { resources: { instruments: 15, data: 3 }, storyline: 'expedition_prep' },
    successText: 'Every instrument sings true. The barometers, the eudiometers, the magnetometers — all calibrated to perfection. Your tools are extensions of your senses.',
    failText: 'Several instruments need repair. You spend more than expected, but the essentials are sound.',
    available: true,
  },

  // === CUMANÁ, JULY 1799 ===
  cumana_temperature: {
    id: 'cumana_temperature', name: 'Establish a Baseline', location: 'cumana',
    description: 'Repeat the 37.7°C sand reading under documented conditions: time, depth, shade and exposure.',
    dieRequired: 2, skill: 'logic', cost: { instruments: 1 },
    effects: { resources: { data: 5 }, flag: 'cumana_baseline', storyline: 'tropical_discovery' },
    successText: 'You record the depth of the thermometer, the position of the sun and the sand temperature. The number is only a beginning; now another observer could repeat it.',
    failText: 'The measurements drift with the changing shade. You record the discrepancy rather than choosing a convenient value.',
    available: true,
  },
  cumana_bonpland: {
    id: 'cumana_bonpland', name: 'Catalogue with Bonpland', location: 'cumana',
    description: 'Compare a living plant to the labels and dried samples brought from Europe.',
    dieRequired: 2, skill: 'aesthetics', cost: { instruments: 1 },
    effects: { resources: { data: 4 }, relationship: { id: 'bonpland', change: 1 }, storyline: 'bonpland_friendship' },
    successText: 'Bonpland explains where the specimen was growing. The place matters more than the shape alone. Together you revise the classification.',
    failText: 'The press damages the leaf. Bonpland insists you draw the surviving specimen before it loses its colour.',
    available: true,
  },
  cumana_listen: {
    id: 'cumana_listen', name: 'Ask Who Knows the Coast', location: 'cumana',
    description: 'Seek local accounts of seasons, floods and the effects of the earthquake. Listen before collecting.',
    dieRequired: 2, skill: 'empathy',
    effects: { resources: { data: 3 }, flag: 'local_testimony', storyline: 'indigenous_knowledge' },
    successText: 'A resident describes the river before and after the earthquake. The account supplies dates, places and uncertainties absent from your maps.',
    failText: 'Your introduction is awkward. You leave without a useful account, but with a better sense of how little permission your passport provides.',
    available: true,
  },
  cumana_specimen: {
    id: 'cumana_specimen', name: 'Investigate a Branching Pattern', location: 'cumana',
    description: 'Compare the pattern of veins in a coastal leaf to the drawing made during the years of preparation.',
    dieRequired: 3, skill: 'logic', cost: { instruments: 2 },
    effects: { resources: { data: 5 }, flag: 'cumana_comparison' },
    successText: 'The resemblance holds at first, then fails under magnification. Something about the branching is similar, but you cannot describe a causal connection.',
    failText: 'The paper has been damaged by humidity. You cannot establish whether the drawings ever truly matched.',
    available: true,
    requiredFlag: 'mystery_correspondence',
  },
  cumana_rest: {
    id: 'cumana_rest', name: 'Rest After the Crossing', location: 'cumana',
    description: 'Prepare the field cases and recover from the weeks aboard ship.',
    dieRequired: 1,
    effects: { resources: { vitality: 8 } },
    successText: 'The doors stay open after sunset. The air cools a little; you sleep with the fieldbook beside you.',
    failText: 'There is too much to hear and too much to see. Even exhausted, you do not sleep for long.',
    available: true,
  },

  // === CARACAS ===
  caracas_explore: {
    id: 'caracas_explore', name: 'Explore the Coast', location: 'caracas',
    description: 'Survey the coastal region, cataloging new species and geological formations.',
    dieRequired: 2, skill: 'aesthetics',
    effects: { resources: { data: 4 }, storyline: 'tropical_discovery' },
    successText: 'The coastal flora is extraordinary! Species you have never seen — orchids of impossible color, trees that seem to breathe moisture from the air itself.',
    failText: 'The heat is oppressive. You collect a few specimens but struggle to focus.',
    available: true,
  },
  caracas_bonpland: {
    id: 'caracas_bonpland', name: 'Work with Bonpland', location: 'caracas',
    description: 'Collaborate with your companion on botanical collection and classification.',
    dieRequired: 2, skill: 'empathy',
    effects: { relationship: { id: 'bonpland', change: 2 }, resources: { data: 3 }, storyline: 'bonpland_friendship' },
    successText: 'Bonpland\'s enthusiasm is infectious. Together you press specimens, debate classifications, and share wonder at the botanical wealth surrounding you.',
    failText: 'A productive session, though you disagree on a classification. Bonpland is stubborn but brilliant.',
    available: true,
  },
  caracas_market: {
    id: 'caracas_market', name: 'Trade at the Market', location: 'caracas',
    description: 'Resupply at the local market. Exchange European goods for local provisions.',
    dieRequired: 1,
    cost: { credits: 5 },
    effects: { resources: { supplies: 15 } },
    successText: 'Good trade. You acquire dried fish, tropical fruits, and a guide who knows the interior paths.',
    failText: 'Prices are high. You get what you can, but your credits dwindle.',
    available: true,
  },
  caracas_rest: {
    id: 'caracas_rest', name: 'Rest in Caracas', location: 'caracas',
    description: 'Recover from the sea voyage in a shaded room with cool water.',
    dieRequired: 1,
    effects: { resources: { vitality: 10 } },
    successText: 'The tropical breeze through an open window. You sleep deeply and wake with renewed strength.',
    failText: 'The heat persists even in sleep. You wake stiff but functional.',
    available: true,
  },
  caracas_collect: {
    id: 'caracas_collect', name: 'Collect Specimens', location: 'caracas',
    description: 'Gather plant and mineral samples for your collection.',
    dieRequired: 3, skill: 'logic',
    cost: { instruments: 2 },
    effects: { resources: { data: 6 }, storyline: 'tropical_discovery' },
    successText: 'A remarkable day of collection! Three species new to European science, plus geological samples that hint at the region\'s volcanic origins.',
    failText: 'The specimens are damaged in the humidity. Some data lost, but the effort itself teaches you about preservation.',
    available: true,
  },

  // === LLANOS ===
  llanos_explore: {
    id: 'llanos_explore', name: 'Traverse the Plains', location: 'llanos',
    description: 'Ride across the vast llanos, observing the ecosystem.',
    dieRequired: 2, skill: 'aesthetics',
    cost: { supplies: 3 },
    effects: { resources: { data: 4 }, storyline: 'llanos_journey' },
    successText: 'The plains unfold like a living painting. You observe the rhythm of the grasslands — seasonal flooding, the migration of herds, the delicate balance of this seemingly empty landscape.',
    failText: 'The sun beats down mercilessly. You see little beyond the shimmer of heat haze.',
    available: true,
  },
  llanos_survive: {
    id: 'llanos_survive', name: 'Find Water & Shelter', location: 'llanos',
    description: 'Locate water sources and safe camping spots on the plains.',
    dieRequired: 2, skill: 'logic',
    effects: { resources: { supplies: 8, vitality: 3 } },
    successText: 'Your knowledge of hydrology pays off. You find a spring where the grass grows slightly greener — underground water close to the surface.',
    failText: 'A long, thirsty day. You find water eventually, but the search costs energy.',
    available: true,
  },
  llanos_llanero: {
    id: 'llanos_llanero', name: 'Speak with the Llaneros', location: 'llanos',
    description: 'Engage with the local horsemen. Learn their knowledge of the land.',
    dieRequired: 3, skill: 'empathy',
    effects: { relationship: { id: 'indigenous', change: 2 }, resources: { data: 3, supplies: 5 }, storyline: 'indigenous_knowledge' },
    successText: 'The llanero shares his knowledge freely once he senses your respect. He shows you where the water hides, when the fish run, how to read the weather in the clouds.',
    failText: 'The llanero is suspicious of foreigners. You exchange only pleasantries.',
    available: true,
  },
  llanos_hunt: {
    id: 'llanos_hunt', name: 'Hunt for Food', location: 'llanos',
    description: 'Hunt capybara or birds to supplement your supplies.',
    dieRequired: 3, skill: 'logic',
    cost: { instruments: 1 },
    effects: { resources: { supplies: 12 } },
    successText: 'A successful hunt. Enough meat to feed the expedition for several days. You also observe the animal\'s behavior — its relationship to the grassland ecosystem.',
    failText: 'The prey is elusive. You return empty-handed but with renewed respect for the difficulty of survival here.',
    available: true,
  },
  llanos_observe: {
    id: 'llanos_observe', name: 'Observe Wildlife', location: 'llanos',
    description: 'Patiently observe the animals of the plains, documenting behavior.',
    dieRequired: 4, skill: 'aesthetics',
    effects: { resources: { data: 7 }, storyline: 'llanos_journey' },
    successText: 'Hours of patient observation reveal the intricate social structure of the capybara herds, the hunting patterns of the jaguars at dusk. This is ecology before the word existed.',
    failText: 'The animals are wary. You catch only glimpses, but each one is precious.',
    available: true,
  },

  // === LAKE VALENCIA ===
  valencia_measure: {
    id: 'valencia_measure', name: 'Measure the Lake', location: 'lake_valencia',
    description: 'Take systematic measurements of water levels, temperature, and surrounding conditions.',
    dieRequired: 3, skill: 'logic',
    cost: { instruments: 3 },
    effects: { resources: { data: 8 }, storyline: 'climate_discovery' },
    successText: 'The data is conclusive. Water levels dropping, humidity decreasing — all correlated with the clearance of forests upstream. You are witnessing human-induced climate change.',
    failText: 'Your measurements are inconsistent. The variables are too many. You need more data.',
    available: true,
  },
  valencia_investigate: {
    id: 'valencia_investigate', name: 'Investigate Deforestation', location: 'lake_valencia',
    description: 'Study the cleared forests upstream and their relationship to the lake.',
    dieRequired: 2, skill: 'logic',
    effects: { resources: { data: 5 }, storyline: 'climate_discovery' },
    successText: 'The connection is clear: trees transpire water into the atmosphere. Remove the trees, remove the rain. The forest and the lake are one system.',
    failText: 'The evidence is suggestive but not conclusive. You mark this as a hypothesis to be tested.',
    available: true,
  },
  valencia_farmer: {
    id: 'valencia_farmer', name: 'Talk to Local Farmers', location: 'lake_valencia',
    description: 'Speak with farmers about the changing landscape.',
    dieRequired: 2, skill: 'empathy',
    effects: { relationship: { id: 'indigenous', change: 1 }, resources: { data: 3 } },
    successText: 'The farmer\'s grandfather remembered when boats sailed where cattle now graze. His testimony confirms your measurements — the change is real, and accelerating.',
    failText: 'The farmer is suspicious of your questions. "The land provides," he says dismissively.',
    available: true,
  },
  valencia_sketch: {
    id: 'valencia_sketch', name: 'Sketch the Landscape', location: 'lake_valencia',
    description: 'Create detailed illustrations of the shrinking lake and its surroundings.',
    dieRequired: 3, skill: 'aesthetics',
    effects: { resources: { data: 4 }, storyline: 'climate_discovery' },
    successText: 'Your sketch captures what numbers cannot — the grief of a wounded landscape. The exposed mudflats, the stumps, the receding water line. Art and science united.',
    failText: 'The landscape is depressing and your hand heavy. The sketch is functional but lacks the power you seek.',
    available: true,
  },
  valencia_rest: {
    id: 'valencia_rest', name: 'Rest by the Lake', location: 'lake_valencia',
    description: 'Camp by the remaining water and recover your strength.',
    dieRequired: 1,
    effects: { resources: { vitality: 8, supplies: -2 } },
    successText: 'The remaining waters lap gently at the shore. You rest, thinking about the connections between all things.',
    failText: 'The mosquitoes are relentless. Sleep is fitful at best.',
    available: true,
  },

  // === ORINOCO ===
  orinoco_navigate: {
    id: 'orinoco_navigate', name: 'Navigate the River', location: 'orinoco',
    description: 'Chart the river\'s course using astronomical instruments.',
    dieRequired: 3, skill: 'logic',
    cost: { instruments: 2 },
    effects: { resources: { data: 6 }, storyline: 'river_mapping' },
    successText: 'Your celestial navigation is flawless. You map a channel connecting the Orinoco to the Amazon — a discovery that reshapes the map of South America.',
    failText: 'Cloud cover prevents observations. You drift, waiting for clear skies.',
    available: true,
  },
  orinoco_eels: {
    id: 'orinoco_eels', name: 'Study Electric Eels', location: 'orinoco',
    description: 'Attempt to capture and study the legendary electric eels.',
    dieRequired: 5, skill: 'logic',
    cost: { instruments: 3, supplies: 5 },
    effects: { resources: { data: 12 }, storyline: 'electric_discovery' },
    successText: 'The indigenous people drive horses into the pool. The eels discharge against the horses\' legs, exhausting their electrical reserves. You collect specimens safely — measuring the most powerful bioelectricity known to science.',
    failText: 'The process is chaotic. You receive a painful shock that leaves your hand numb. Some specimens are lost in the struggle.',
    available: true,
  },
  orinoco_indigenous: {
    id: 'orinoco_indigenous', name: 'Learn from Indigenous Guides', location: 'orinoco',
    description: 'Exchange knowledge with the peoples who have lived here for millennia.',
    dieRequired: 3, skill: 'empathy',
    effects: { relationship: { id: 'indigenous', change: 3 }, resources: { data: 5, supplies: 5 }, storyline: 'indigenous_knowledge' },
    successText: 'Your respect opens doors. The guides share their names for species — each encoding ecological relationships. Their agricultural practices sustain rather than deplete. You realize European science has much to learn.',
    failText: 'The language barrier is significant. You communicate through gestures and shared observation.',
    available: true,
  },
  orinoco_collect: {
    id: 'orinoco_collect', name: 'Collect River Specimens', location: 'orinoco',
    description: 'Gather aquatic specimens from the river\'s rich waters.',
    dieRequired: 2, skill: 'logic',
    cost: { instruments: 2 },
    effects: { resources: { data: 5 }, storyline: 'tropical_discovery' },
    successText: 'The river teems with life. Fish of impossible colors, plants that float and dive, insects that skate on the surface. Each specimen a new entry in the catalog of nature.',
    failText: 'The water is murky and the specimens few. But even failure teaches — you learn about the river\'s seasonal rhythms.',
    available: true,
  },
  orinoco_rest: {
    id: 'orinoco_rest', name: 'Rest on the Riverbank', location: 'orinoco',
    description: 'Make camp on the bank and recover from the journey.',
    dieRequired: 1,
    effects: { resources: { vitality: 6 } },
    successText: 'The river\'s song carries you to sleep. You dream in Portuguese and Spanish, in the language of water.',
    failText: 'The humidity is suffocating. Insects swarm. You rest, but do not recover.',
    available: true,
  },

  // === ANDES ===
  andes_climb: {
    id: 'andes_climb', name: 'Climb Higher', location: 'andes_foothills',
    description: 'Ascend further into the mountains, observing vegetation zones.',
    dieRequired: 3, skill: 'logic',
    cost: { supplies: 4, vitality: -3 },
    effects: { resources: { data: 7 }, storyline: 'altitudinal_zonation' },
    successText: 'Each hundred meters brings a new world. Tropical palms give way to oaks, then conifers, then mosses. You are climbing through the climate zones of an entire continent compressed into a single mountain.',
    failText: 'The altitude takes its toll. You turn back, gasping, but the data you gathered is valuable.',
    available: true,
  },
  andes_measure: {
    id: 'andes_measure', name: 'Take Barometric Readings', location: 'andes_foothills',
    description: 'Measure atmospheric pressure at various altitudes.',
    dieRequired: 4, skill: 'logic',
    cost: { instruments: 3 },
    effects: { resources: { data: 8 }, storyline: 'altitudinal_zonation' },
    successText: 'The barometric formula emerges from your data — the precise mathematical relationship between altitude and pressure. This will allow calculations of ocean depth from surface measurements.',
    failText: 'The cold makes your fingers clumsy. Some readings are unreliable, but the pattern is visible.',
    available: true,
  },
  andes_observe: {
    id: 'andes_observe', name: 'Document Vegetation Zones', location: 'andes_foothills',
    description: 'Catalog the changing plant life as you ascend.',
    dieRequired: 3, skill: 'aesthetics',
    effects: { resources: { data: 6 }, storyline: 'altitudinal_zonation' },
    successText: 'Each zone is a different garden, a different world. Your sketches capture not just species but the character of each altitude — the mood, the quality of light, the sound of wind through different leaves.',
    failText: 'The transitions blur. You struggle to capture the subtle boundaries between zones.',
    available: true,
  },
  andes_guide: {
    id: 'andes_guide', name: 'Consult Mountain Guide', location: 'andes_foothills',
    description: 'Speak with local guides about the path to Chimborazo.',
    dieRequired: 3, skill: 'empathy',
    effects: { relationship: { id: 'indigenous', change: 2 }, flag: 'reached_andes', storyline: 'chimborazo_prep' },
    successText: 'The guide studies your face and sees determination. "You are different from the others," he says. "I will take you as high as the mountain allows." The path to Chimborazo opens.',
    failText: 'The guide is cautious. "The mountain kills the unprepared," he warns. But he gives you directions.',
    available: true,
  },
  andes_rest: {
    id: 'andes_rest', name: 'Rest at Camp', location: 'andes_foothills',
    description: 'Recover at base camp before attempting higher altitudes.',
    dieRequired: 1,
    effects: { resources: { vitality: 10 } },
    successText: 'The mountain air, though thin, is invigorating. You sleep deeply and wake with clear eyes.',
    failText: 'The cold seeps into your bones. Sleep is fitful, punctuated by dreams of falling.',
    available: true,
  },

  // === CHIMBORAZO ===
  chimborazo_ascent: {
    id: 'chimborazo_ascent', name: 'Attempt the Summit', location: 'chimborazo',
    description: 'The final push to the top of the world. Everything leads to this.',
    dieRequired: 5, skill: 'logic',
    cost: { supplies: 8, instruments: 5, vitality: -10 },
    effects: { resources: { data: 15 }, flag: 'summit_reached', storyline: 'chimborazo_ascent' },
    successText: '19,286 feet. You stand higher than any human in history. The world curves below you. The air is so thin each breath is a victory. You have touched the sky.',
    failText: 'Altitude sickness overwhelms you. 500 feet from the summit, you must turn back. The mountain will keep its secret — for now.',
    available: true,
  },
  chimborazo_measure: {
    id: 'chimborazo_measure', name: 'Measure at Altitude', location: 'chimborazo',
    description: 'Take scientific readings at extreme altitude.',
    dieRequired: 4, skill: 'logic',
    cost: { instruments: 4 },
    effects: { resources: { data: 10 }, storyline: 'chimborazo_ascent' },
    successText: 'Every reading is precious. The thermometer, the barometer, the eudiometer — each instrument tells part of the story of this altitude. The data will rewrite the textbooks.',
    failText: 'The cold seizes your instruments. Mercury contracts unpredictably. Some data is lost to the mountain.',
    available: true,
  },
  chimborazo_naturgemalde: {
    id: 'chimborazo_naturgemalde', name: 'Create the Naturgemälde', location: 'chimborazo',
    description: 'Synthesize all your observations into the great painting of nature.',
    dieRequired: 5, skill: 'aesthetics',
    cost: { instruments: 2 },
    effects: { resources: { data: 20 }, flag: 'naturgemalde_complete', storyline: 'naturgemalde_creation' },
    successText: 'The painting takes shape — a cross-section of the mountain showing every zone of life, from tropical base to eternal ice. It is both scientific diagram and work of art. It is the most beautiful thing you have ever created.',
    failText: 'The synthesis eludes you. Too much data, too many observations. The fragments refuse to cohere into a unified vision.',
    available: true,
    requiredFlag: 'summit_reached',
  },
  chimborazo_survive: {
    id: 'chimborazo_survive', name: 'Endure the Cold', location: 'chimborazo',
    description: 'Fight against hypothermia and altitude sickness.',
    dieRequired: 3, skill: 'logic',
    effects: { resources: { vitality: 8 } },
    successText: 'You know the signs of altitude sickness. You breathe steadily, keep moving, drink melted snow. Your body adapts, if slowly.',
    failText: 'The cold is an enemy you cannot fight with instruments alone. You lose feeling in your fingers.',
    available: true,
  },
  chimborazo_rest: {
    id: 'chimborazo_rest', name: 'Rest at High Camp', location: 'chimborazo',
    description: 'Recover at the high camp between summit attempts.',
    dieRequired: 1,
    cost: { supplies: 3 },
    effects: { resources: { vitality: 12 } },
    successText: 'Wrapped in furs, sipping coca tea, you rest. The stars above are impossibly bright. You understand why the ancients worshipped mountains.',
    failText: 'Sleep comes in fragments. The altitude makes every breath a conscious effort.',
    available: true,
  },

  // === MEXICO ===
  mexico_survey: {
    id: 'mexico_survey', name: 'Survey the Territory', location: 'mexico',
    description: 'Chart the roads and geography of New Spain with precision.',
    dieRequired: 3, skill: 'logic',
    cost: { instruments: 3 },
    effects: { resources: { data: 8 }, storyline: 'colonial_survey' },
    successText: 'Your elevation profiles are masterworks of precision. Every hill, every river, every road mapped with unprecedented accuracy. This data will reshape European understanding of the Americas.',
    failText: 'The terrain is complex and your instruments struggle with the extreme variations. The survey is incomplete.',
    available: true,
  },
  mexico_mine: {
    id: 'mexico_mine', name: 'Analyze the Silver Mine', location: 'mexico',
    description: 'Study the Valenciana mine — its geology, economics, and human cost.',
    dieRequired: 4, skill: 'political',
    cost: { vitality: -5 },
    effects: { resources: { data: 10, credits: 10 }, storyline: 'colonial_critique' },
    successText: 'Three days in the mine reveal everything — the geological richness, the economic system, the human cost. Your analysis is balanced, damning, and irrefutable.',
    failText: 'The darkness and suffering overwhelm your objectivity. You record data but struggle to maintain the detachment of science.',
    available: true,
  },
  mexico_jefferson: {
    id: 'mexico_jefferson', name: 'Meet President Jefferson', location: 'mexico',
    description: 'Share your geographic knowledge with the American president.',
    dieRequired: 4, skill: 'political',
    effects: { resources: { credits: 15, data: 5 }, relationship: { id: 'scientific_community', change: 2 }, storyline: 'colonial_survey' },
    successText: 'Jefferson is fascinated by your data. You share maps, measurements, and observations. In return, he shares his vision for the new nation. A meeting of minds across the Atlantic.',
    failText: 'The meeting is cordial but superficial. Jefferson is interested in data, not philosophy. You exchange pleasantries and maps.',
    available: true,
  },
  mexico_political: {
    id: 'mexico_political', name: 'Observe Colonial Society', location: 'mexico',
    description: 'Study the social structures of New Spain — the inequalities, the contradictions.',
    dieRequired: 3, skill: 'political',
    effects: { resources: { data: 6 }, storyline: 'colonial_critique' },
    successText: 'You see clearly now — the Enlightenment ideals of Europe, proclaimed so loudly, ring hollow in the colonies. Liberty for some, bondage for others. You document everything.',
    failText: 'The complexity of colonial society resists easy analysis. You observe but do not yet understand.',
    available: true,
  },
  mexico_rest: {
    id: 'mexico_rest', name: 'Rest in Mexico City', location: 'mexico',
    description: 'Recover in the grand capital of New Spain.',
    dieRequired: 1,
    cost: { credits: 5 },
    effects: { resources: { vitality: 10, supplies: 5 } },
    successText: 'The city\'s grandeur is restorative. Good food, clean water, intellectual conversation. You remember why you began this journey.',
    failText: 'The city is expensive and the food heavy. You rest, but do not fully recover.',
    available: true,
  },

  // === PARIS ===
  paris_write: {
    id: 'paris_write', name: 'Write Your Findings', location: 'paris',
    description: 'Transform your field notes into publishable scientific works.',
    dieRequired: 3, skill: 'logic',
    effects: { resources: { data: 8 }, storyline: 'publication' },
    successText: 'The words flow. Five years of observation distilled into clear, elegant prose. Your narrative of travel will become one of the most influential scientific works of the century.',
    failText: 'The material is vast and unwieldy. You write, cross out, rewrite. Progress is slow.',
    available: true,
  },
  paris_goethe: {
    id: 'paris_goethe', name: 'Meet with Goethe', location: 'paris',
    description: 'Correspond and meet with your great friend, the poet-scientist.',
    dieRequired: 3, skill: 'aesthetics',
    effects: { relationship: { id: 'goethe', change: 3 }, resources: { data: 5 }, storyline: 'goethe_synthesis' },
    successText: 'Goethe embraces you. "You have shown me what I always felt — that nature is a poem." Together you discuss the unity of knowledge, the marriage of science and art. These conversations will shape your masterwork.',
    failText: 'The meeting is brief but warm. Goethe is busy with his own projects, but his encouragement sustains you.',
    available: true,
  },
  paris_lecture: {
    id: 'paris_lecture', name: 'Deliver a Lecture', location: 'paris',
    description: 'Share your discoveries with the scientific community.',
    dieRequired: 4, skill: 'empathy',
    effects: { resources: { credits: 10, data: 5 }, relationship: { id: 'scientific_community', change: 2 }, storyline: 'publication' },
    successText: 'The lecture hall is packed. Your words paint pictures of tropical forests, volcanic peaks, electric eels. The audience is transfixed. You have made science popular.',
    failText: 'Nerves get the better of you. The lecture is informative but lacks the poetry that makes your writing sing.',
    available: true,
  },
  paris_darwin: {
    id: 'paris_darwin', name: 'Mentor Young Darwin', location: 'paris',
    description: 'A young naturalist named Charles seeks your counsel before his own voyage.',
    dieRequired: 4, skill: 'empathy',
    effects: { relationship: { id: 'scientific_community', change: 3 }, storyline: 'legacy' },
    successText: 'Darwin\'s eyes burn with the same fire you once had. "Take careful measurements," you tell him, "but remember — seek the connections. The web of life is the great mystery." He will remember.',
    failText: 'The young man is eager but unfocused. You offer what advice you can, hoping it takes root.',
    available: true,
  },
  paris_kosmos: {
    id: 'paris_kosmos', name: 'Write Kosmos', location: 'paris',
    description: 'Your final and greatest work — the unification of all knowledge.',
    dieRequired: 6, skill: 'aesthetics',
    effects: { resources: { data: 25 }, flag: 'kosmos_written', storyline: 'kosmos' },
    successText: 'Kosmos is complete. Five volumes that unite astronomy and geography, physics and poetry, data and beauty. You have shown the world that nature is a living, breathing whole. Your life\'s work is done.',
    failText: 'The synthesis remains incomplete. The threads of knowledge are too many, too complex. But each attempt brings you closer.',
    available: true,
    requiredFlag: 'naturgemalde_complete',
  },

  // === NEW ACTIONS FROM "THE INVENTION OF NATURE" ===

  // Berlin - Goethe meeting
  berlin_goethe: {
    id: 'berlin_goethe', name: 'Meet Goethe in Jena', location: 'berlin',
    description: 'Travel to Jena to meet the great poet-scientist Johann Wolfgang von Goethe. A pivotal encounter.',
    dieRequired: 3, skill: 'aesthetics',
    cost: { credits: 5 },
    effects: { relationship: { id: 'goethe', change: 3 }, resources: { data: 5 }, flag: 'goethe_met', storyline: 'goethe_synthesis' },
    successText: 'Goethe embraces you as a kindred spirit. "You see nature as I do — not as a machine, but as a living poem." He teaches you to merge aesthetic appreciation with scientific rigor. This meeting will shape your entire career.',
    failText: 'The meeting is brief but inspiring. Goethe is busy with his own work, but his encouragement plants seeds that will bloom for decades.',
    available: true,
  },

  // Caracas - Humboldt Current
  caracas_humboldt_current: {
    id: 'caracas_humboldt_current', name: 'Study the Humboldt Current', location: 'caracas',
    description: 'Measure the cold ocean current that flows north along the coast, later named after you.',
    dieRequired: 4, skill: 'logic',
    cost: { instruments: 2 },
    effects: { resources: { data: 8 }, storyline: 'ocean_currents' },
    successText: 'You document the cold current flowing north from Antarctica, bringing nutrients that sustain entire ecosystems. This discovery will reshape understanding of oceanography and climate. The "Humboldt Current" will bear your name forever.',
    failText: 'The measurements are difficult in the tropical heat, but you gather enough data to note the current\'s unusual cold temperature.',
    available: true,
  },

  // Cuba - New location actions
  cuba_explore: {
    id: 'cuba_explore', name: 'Explore Cuban Flora', location: 'cuba',
    description: 'Catalog the rich biodiversity of this Caribbean island.',
    dieRequired: 2, skill: 'logic',
    effects: { resources: { data: 5 }, storyline: 'tropical_discovery' },
    successText: 'Cuba\'s flora is extraordinary — orchids, palms, and medicinal plants unknown to European science. You collect specimens and sketch the landscape with meticulous care.',
    failText: 'The heat and humidity make fieldwork exhausting. You collect some specimens but struggle with preservation.',
    available: true,
  },
  cuba_slavery: {
    id: 'cuba_slavery', name: 'Document Enslavement', location: 'cuba',
    description: 'Observe and record the brutal reality of slavery in the sugar plantations.',
    dieRequired: 3, skill: 'political',
    effects: { resources: { data: 6, vitality: -5 }, storyline: 'colonial_critique' },
    successText: 'What you witness horrifies you. Enslaved Africans toil under brutal conditions, their bodies broken by labor. You document everything — the human cost of colonial wealth. This will fuel your lifelong opposition to slavery.',
    failText: 'The reality is overwhelming. You observe but struggle to maintain the detachment needed for scientific documentation.',
    available: true,
  },
  cuba_collect: {
    id: 'cuba_collect', name: 'Collect Geological Samples', location: 'cuba',
    description: 'Study the island\'s geology and collect mineral specimens.',
    dieRequired: 3, skill: 'logic',
    cost: { instruments: 2 },
    effects: { resources: { data: 6 }, storyline: 'tropical_discovery' },
    successText: 'Cuba\'s geology reveals its volcanic origins. You collect samples that will help reconstruct the Caribbean\'s geological history.',
    failText: 'The samples are interesting but the analysis will require more time and better equipment.',
    available: true,
  },
  cuba_rest: {
    id: 'cuba_rest', name: 'Rest in Havana', location: 'cuba',
    description: 'Recover in the colonial capital before continuing your journey.',
    dieRequired: 1,
    cost: { credits: 5 },
    effects: { resources: { vitality: 10, supplies: 5 } },
    successText: 'Havana\'s grandeur is restorative. Good food, clean water, intellectual conversation with local scholars. You recover your strength.',
    failText: 'The city is expensive and the food heavy. You rest, but do not fully recover.',
    available: true,
  },
  cuba_magnetic: {
    id: 'cuba_magnetic', name: 'Measure Magnetic Declination', location: 'cuba',
    description: 'Study the Earth\'s magnetic field, mapping the magnetic equator.',
    dieRequired: 4, skill: 'logic',
    cost: { instruments: 3 },
    effects: { resources: { data: 8 }, storyline: 'magnetic_research' },
    successText: 'Your measurements of magnetic declination are precise. You map the magnetic equator, a line of zero magnetic inclination. This work will advance geomagnetism significantly.',
    failText: 'The instruments are affected by the tropical heat. Some readings are unreliable, but the pattern emerges.',
    available: true,
  },

  // Mexico - Aztec heritage
  mexico_aztec: {
    id: 'mexico_aztec', name: 'Study Aztec Heritage', location: 'mexico',
    description: 'Investigate the remnants of Aztec civilization and their relationship to the land.',
    dieRequired: 3, skill: 'aesthetics',
    effects: { resources: { data: 6 }, storyline: 'colonial_survey' },
    successText: 'The Aztec ruins speak of a sophisticated civilization that understood the land intimately. Their agricultural systems, their calendar, their cosmology — all reveal a deep connection to nature that the Spanish conquest has obscured.',
    failText: 'The ruins are impressive but their full meaning eludes you. You sketch what you can.',
    available: true,
  },

  // Washington D.C. - Jefferson meeting
  washington_jefferson: {
    id: 'washington_jefferson', name: 'Meet President Jefferson', location: 'washington',
    description: 'Share your discoveries about New Spain with the American president. A meeting of Enlightenment minds.',
    dieRequired: 4, skill: 'political',
    effects: { resources: { credits: 20, data: 8 }, relationship: { id: 'scientific_community', change: 3 }, storyline: 'colonial_survey' },
    successText: 'Jefferson is fascinated by your data. You share maps, measurements, and observations about New Spain. He provides you with 19 pages of data about the American West. A meeting of minds across the Atlantic.',
    failText: 'The meeting is cordial but superficial. Jefferson is interested in data, not philosophy. You exchange pleasantries and maps.',
    available: true,
  },
  washington_slavery: {
    id: 'washington_slavery', name: 'Confront American Slavery', location: 'washington',
    description: 'Observe the contradiction of a nation founded on liberty yet practicing slavery.',
    dieRequired: 3, skill: 'political',
    effects: { resources: { data: 5, vitality: -3 }, storyline: 'colonial_critique' },
    successText: 'You see the same contradiction here as in Cuba — a nation proclaiming liberty while holding millions in bondage. You note this in your writings, though carefully. The hypocrisy of the Enlightenment is everywhere.',
    failText: 'The topic is too sensitive to discuss openly. You observe but do not speak.',
    available: true,
  },
  washington_data: {
    id: 'washington_data', name: 'Share Western Data', location: 'washington',
    description: 'Provide Jefferson with detailed geographic information about the American West.',
    dieRequired: 3, skill: 'logic',
    effects: { resources: { data: 6, credits: 10 }, storyline: 'colonial_survey' },
    successText: 'Your maps and measurements of the American West are invaluable to Jefferson. He uses this data to plan the Lewis and Clark expedition. Your science serves exploration.',
    failText: 'The data is useful but incomplete. Jefferson is grateful but wants more.',
    available: true,
  },
  washington_rest: {
    id: 'washington_rest', name: 'Rest in Washington', location: 'washington',
    description: 'Recover in the young American capital.',
    dieRequired: 1,
    cost: { credits: 5 },
    effects: { resources: { vitality: 8 } },
    successText: 'The city is rough but hopeful. You rest and reflect on the contradictions of this new nation.',
    failText: 'The accommodations are basic. You rest, but the political tensions weigh on you.',
    available: true,
  },

  // Berlin Later Years
  berlin_court: {
    id: 'berlin_court', name: 'Attend the Royal Court', location: 'berlin_later',
    description: 'Fulfill your duties as a royal chamberlain. The court expects your presence.',
    dieRequired: 2, skill: 'political',
    cost: { vitality: -2 },
    effects: { resources: { credits: 15 }, relationship: { id: 'scientific_community', change: -1 } },
    successText: 'You navigate the court\'s intrigues with diplomatic skill. The king is pleased, but you feel the weight of compromise. Your time could be better spent on science.',
    failText: 'The court\'s conservatism frustrates you. You attend out of duty but chafe at the constraints.',
    available: true,
  },
  berlin_russia_prep: {
    id: 'berlin_russia_prep', name: 'Prepare for Russia Expedition', location: 'berlin_later',
    description: 'At age 60, prepare for your final great expedition across the Russian Empire.',
    dieRequired: 4, skill: 'logic',
    cost: { credits: 20, instruments: 5 },
    effects: { resources: { data: 5 }, flag: 'russia_expedition', storyline: 'russia_expedition' },
    successText: 'Despite your age, your preparations are meticulous. The Tsar has invited you to explore his vast empire. This will be your last great adventure.',
    failText: 'The preparations are extensive. You worry about your age, but the call of exploration is irresistible.',
    available: true,
  },
  berlin_legacy: {
    id: 'berlin_legacy', name: 'Mentor Young Scientists', location: 'berlin_later',
    description: 'Guide the next generation of naturalists, including a young Charles Darwin.',
    dieRequired: 3, skill: 'empathy',
    effects: { relationship: { id: 'scientific_community', change: 2 }, resources: { data: 4 }, storyline: 'legacy' },
    successText: 'Young Darwin visits, eager for guidance. You encourage him to read your travel narratives. "Go see for yourself," you tell him. He will remember your words when he boards the Beagle.',
    failText: 'The young scientists are eager but unfocused. You offer what advice you can.',
    available: true,
  },
  berlin_rest_later: {
    id: 'berlin_rest_later', name: 'Rest in Berlin', location: 'berlin_later',
    description: 'Recover from the demands of court and science.',
    dieRequired: 1,
    effects: { resources: { vitality: 10 } },
    successText: 'You rest in your apartment, surrounded by books and specimens. The weight of decades lifts, if only briefly.',
    failText: 'Sleep is fitful. Dreams of mountains and jungles. The past is always present.',
    available: true,
  },
  berlin_1848: {
    id: 'berlin_1848', name: 'Witness the 1848 Revolutions', location: 'berlin_later',
    description: 'At age 79, witness the revolutionary fervor sweeping Europe.',
    dieRequired: 3, skill: 'political',
    effects: { resources: { data: 5, vitality: -5 }, storyline: 'political_ideals' },
    successText: 'You support the revolutionaries from your window, though your liberal ideals conflict with your court position. The old world is changing. You feel both hope and sorrow.',
    failText: 'The violence disturbs you. You are too old for revolution, but your heart is with the people.',
    available: true,
  },

  // Russia Expedition
  russia_explore: {
    id: 'russia_explore', name: 'Traverse the Steppes', location: 'russia',
    description: 'Cross the vast Russian steppes, from the Urals to the Altai Mountains.',
    dieRequired: 3, skill: 'logic',
    cost: { supplies: 5, vitality: -3 },
    effects: { resources: { data: 7 }, storyline: 'russia_expedition' },
    successText: 'The steppes stretch to infinity. You measure, observe, and document with the same precision as in South America. The landscape is different, but nature\'s laws are universal.',
    failText: 'The journey is exhausting. The cold and distance test your aging body.',
    available: true,
  },
  russia_gold: {
    id: 'russia_gold', name: 'Study Gold Deposits', location: 'russia',
    description: 'Investigate the gold deposits of the Urals for the Tsar.',
    dieRequired: 4, skill: 'logic',
    cost: { instruments: 3 },
    effects: { resources: { credits: 25, data: 6 }, storyline: 'russia_expedition' },
    successText: 'Your geological expertise identifies rich gold deposits. The Tsar is pleased and rewards you generously. Your science serves empire, though you question the cost.',
    failText: 'The deposits are promising but the analysis requires more time. The Tsar is impatient.',
    available: true,
  },
  russia_climate: {
    id: 'russia_climate', name: 'Study Continental Climate', location: 'russia',
    description: 'Compare the extreme continental climate of Russia with tropical climates.',
    dieRequired: 4, skill: 'logic',
    cost: { instruments: 3 },
    effects: { resources: { data: 8 }, storyline: 'climate_discovery' },
    successText: 'The contrast is striking — from tropical Venezuela to the frozen steppes. You document how distance from the ocean creates extreme temperature variations. Climate is truly global.',
    failText: 'The cold makes measurements difficult. Some data is lost to frost.',
    available: true,
  },
  russia_survive: {
    id: 'russia_survive', name: 'Endure the Cold', location: 'russia',
    description: 'Survive the brutal Russian winter at age 60.',
    dieRequired: 3, skill: 'logic',
    effects: { resources: { vitality: 5 } },
    successText: 'You wrap yourself in furs and keep moving. The cold is an old enemy. Your body adapts, if slowly.',
    failText: 'The cold seeps into your bones. You are not as young as you once were.',
    available: true,
  },
  russia_observe: {
    id: 'russia_observe', name: 'Observe Asian Flora', location: 'russia',
    description: 'Document the plant life of Central Asia, comparing it to other regions.',
    dieRequired: 3, skill: 'aesthetics',
    effects: { resources: { data: 6 }, storyline: 'russia_expedition' },
    successText: 'The flora of Central Asia reveals connections to both European and Asian species. Nature knows no borders. Your observations support your theory of global interconnectedness.',
    failText: 'The growing season is short. You observe what you can before the frost returns.',
    available: true,
  },

  // Paris - Publishing
  paris_publish: {
    id: 'paris_publish', name: 'Publish Travel Narrative', location: 'paris',
    description: 'Publish your account of the American journey — a work that will become a bestseller.',
    dieRequired: 4, skill: 'aesthetics',
    effects: { resources: { credits: 30, data: 8 }, relationship: { id: 'scientific_community', change: 2 }, storyline: 'publication' },
    successText: 'Your travel narrative becomes a sensation. Readers across Europe are captivated by your vivid descriptions of tropical forests, volcanic peaks, and electric eels. You have made science popular.',
    failText: 'The publication is well-received but does not achieve the widespread fame you hoped for. Still, it establishes your reputation.',
    available: true,
  },

  // === BONPLAND ACTIONS ===
  bonpland_botanical: {
    id: 'bonpland_botanical',
    name: 'Collaborate with Bonpland on Botany',
    location: 'caracas',
    description: 'Work with your companion to classify the extraordinary plant specimens you\'ve collected.',
    dieRequired: 3,
    skill: 'empathy',
    cost: { supplies: 2 },
    effects: {
      resources: { data: 8 },
      relationship: { id: 'bonpland', change: 2 },
      bonpland: { morale: 5, expertise: 3 },
    },
    successText: 'Bonpland\'s expertise in botany complements your broad vision perfectly. Together you classify dozens of new species, your conversation flowing between scientific precision and shared wonder.',
    failText: 'The work is tedious and the heat oppressive. You and Bonpland make progress, but the pace is slower than hoped.',
    available: true,
  },
  bonpland_morale: {
    id: 'bonpland_morale',
    name: 'Boost Bonpland\'s Spirits',
    location: 'any',
    description: 'Your companion\'s morale is flagging. Spend time encouraging him and reminding him of your shared purpose.',
    dieRequired: 2,
    skill: 'empathy',
    effects: {
      relationship: { id: 'bonpland', change: 3 },
      bonpland: { morale: 15 },
    },
    successText: 'You remind Bonpland of the importance of your work, of the lives that will be touched by your discoveries. His eyes light up with renewed purpose. "You are right, Alexander. We must continue."',
    failText: 'Bonpland appreciates your words, but the hardship has worn him down. He nods politely, but his heart is not yet restored.',
    available: true,
  },
  bonpland_health: {
    id: 'bonpland_health',
    name: 'Care for Bonpland\'s Health',
    location: 'any',
    description: 'Your companion is struggling. Use your knowledge of medicine and your supplies to nurse him back to health.',
    dieRequired: 3,
    skill: 'logic',
    cost: { supplies: 5, instruments: 2 },
    effects: {
      relationship: { id: 'bonpland', change: 2 },
      bonpland: { health: 20 },
    },
    successText: 'Your careful attention and medical knowledge restore Bonpland\'s strength. He rests, eats the nourishing food you prepare, and within days his color returns. "Thank you, my friend," he says.',
    failText: 'You do what you can, but Bonpland\'s condition improves only slightly. He needs more time and better care than you can provide on the trail.',
    available: true,
  },
};

// ===== STORYLINES (parallel arcs like Citizen Sleeper) =====
export const initialStorylines: Storyline[] = [
  {
    id: 'expedition_prep', title: 'The Expedition Prepares', icon: '🧭',
    description: 'Prepare for the journey to the New World.',
    currentStage: 0,
    stages: [
      { id: 'prep_1', title: 'Study & Plan', description: 'Research the route and prepare your mind.', requirement: { type: 'action', target: 'berlin_prepare' }, text: 'Your preparations take shape. Maps cover every surface of your study.', completed: false },
      { id: 'prep_2', title: 'Instruments Ready', description: 'Calibrate all 42 instruments.', requirement: { type: 'action', target: 'berlin_instruments' }, text: 'Every instrument sings true. You are ready.', completed: false, reward: { flag: 'expedition_ready' } },
    ],
  },
  {
    id: 'bonpland_friendship', title: 'Bonpland\'s Friendship', icon: '🌱',
    description: 'Build your partnership with Aimé Bonpland.',
    currentStage: 0,
    stages: [
      { id: 'bon_1', title: 'First Collaboration', description: 'Work together on botanical collection.', requirement: { type: 'action', target: 'caracas_bonpland' }, text: 'Bonpland\'s enthusiasm is infectious. A partnership forms.', completed: false },
      { id: 'bon_2', title: 'Deepening Trust', description: 'Share your vision of unified science.', requirement: { type: 'relationship', target: 'bonpland', value: 4 }, text: 'Bonpland understands your vision. "We see the world differently, but we see it together."', completed: false, reward: { relationship: { id: 'bonpland', change: 2 } } },
      { id: 'bon_3', title: 'Partners for Life', description: 'Your bond is unbreakable.', requirement: { type: 'relationship', target: 'bonpland', value: 7 }, text: 'Through hardship and wonder, your friendship has become the foundation of the expedition.', completed: false, reward: { flag: 'bonpland_partner' } },
    ],
  },
  {
    id: 'climate_discovery', title: 'Forests & Climate', icon: '🌳',
    description: 'Discover the connection between deforestation and climate.',
    currentStage: 0,
    stages: [
      { id: 'clim_1', title: 'The Shrinking Lake', description: 'Notice Lake Valencia\'s recession.', requirement: { type: 'action', target: 'valencia_measure' }, text: 'The data is clear. The lake is shrinking. But why?', completed: false },
      { id: 'clim_2', title: 'The Forest Connection', description: 'Link deforestation to reduced rainfall.', requirement: { type: 'data', target: 'data', value: 25 }, text: 'The trees breathe water into the sky. Remove the trees, remove the rain. You have discovered human-induced climate change.', completed: false, reward: { flag: 'climate_discovered' } },
    ],
  },
  {
    id: 'indigenous_knowledge', title: 'Voices of the Land', icon: '🪶',
    description: 'Learn from the peoples who have lived here for millennia.',
    currentStage: 0,
    stages: [
      { id: 'ind_1', title: 'First Contact', description: 'Begin building relationships with indigenous peoples.', requirement: { type: 'relationship', target: 'indigenous', value: 2 }, text: 'Trust is slowly earned. They begin to share their knowledge.', completed: false },
      { id: 'ind_2', title: 'Deep Knowledge', description: 'Gain significant indigenous trust.', requirement: { type: 'relationship', target: 'indigenous', value: 5 }, text: 'Their ecological knowledge is vast — centuries of observation encoded in language and practice.', completed: false, reward: { flag: 'indigenous_ally' } },
      { id: 'ind_3', title: 'Two Ways of Knowing', description: 'Synthesize European and indigenous knowledge.', requirement: { type: 'relationship', target: 'indigenous', value: 8 }, text: 'You understand now: science is not the only path to knowledge. The web of life is known in many languages.', completed: false, reward: { flag: 'knowledge_synthesis' } },
    ],
  },
  {
    id: 'altitudinal_zonation', title: 'The Mountain\'s Layers', icon: '⛰️',
    description: 'Document the vegetation zones of the Andes.',
    currentStage: 0,
    stages: [
      { id: 'alt_1', title: 'First Ascent', description: 'Begin climbing into the mountains.', requirement: { type: 'action', target: 'andes_climb' }, text: 'Each step upward reveals a new world. The vegetation changes like pages in a book.', completed: false },
      { id: 'alt_2', title: 'The Pattern Emerges', description: 'Map the vegetation zones systematically.', requirement: { type: 'data', target: 'data', value: 50 }, text: 'The pattern is clear: altitude creates climate, climate creates ecology. Every mountain is a compressed continent.', completed: false, reward: { flag: 'zonation_mapped' } },
    ],
  },
  {
    id: 'chimborazo_ascent', title: 'The Summit of the World', icon: '🌋',
    description: 'Attempt the record-breaking ascent of Chimborazo.',
    currentStage: 0,
    stages: [
      { id: 'chim_1', title: 'The Attempt', description: 'Push for the summit.', requirement: { type: 'flag', target: 'summit_reached' }, text: '19,286 feet. You stand higher than any human in history. The world curves below you.', completed: false, reward: { flag: 'summit_reached' } },
    ],
  },
  {
    id: 'naturgemalde_creation', title: 'The Painting of Nature', icon: '🖼️',
    description: 'Create your masterwork — the Naturgemälde.',
    currentStage: 0,
    stages: [
      { id: 'nat_1', title: 'The Vision', description: 'Synthesize all observations into a unified image.', requirement: { type: 'flag', target: 'naturgemalde_complete' }, text: 'The Naturgemälde takes shape — a cross-section of Chimborazo showing all life, from base to summit, in one unified vision.', completed: false },
    ],
  },
  {
    id: 'colonial_critique', title: 'The Colonial Critique', icon: '⚖️',
    description: 'Document and critique the colonial system.',
    currentStage: 0,
    stages: [
      { id: 'col_1', title: 'Observation', description: 'Begin documenting colonial realities.', requirement: { type: 'action', target: 'mexico_political' }, text: 'The contradictions of empire are everywhere. Liberty proclaimed, bondage practiced.', completed: false },
      { id: 'col_2', title: 'The Mine\'s Truth', description: 'Document the human cost of silver.', requirement: { type: 'action', target: 'mexico_mine' }, text: 'The Valenciana mine reveals everything — wealth built on suffering, progress measured in lives.', completed: false, reward: { flag: 'colonial_documented' } },
    ],
  },
  {
    id: 'kosmos', title: 'Kosmos', icon: '✦',
    description: 'Write your masterwork unifying all of nature.',
    currentStage: 0,
    stages: [
      { id: 'kos_1', title: 'The Great Work', description: 'Complete Kosmos.', requirement: { type: 'flag', target: 'kosmos_written' }, text: 'Kosmos is complete. You have unified all knowledge into a single vision of nature as a living whole.', completed: false },
    ],
  },
  {
    id: 'goethe_synthesis', title: 'The Goethe Synthesis', icon: '🪶',
    description: 'Merge science and poetry under Goethe\'s guidance.',
    currentStage: 0,
    stages: [
      { id: 'goethe_1', title: 'Meeting the Master', description: 'Meet Goethe and learn his approach.', requirement: { type: 'flag', target: 'goethe_met' }, text: 'Goethe teaches you to see nature as both scientist and poet. "The eye sees what it is prepared to understand."', completed: false },
      { id: 'goethe_2', title: 'Art and Science United', description: 'Build a deep friendship with Goethe.', requirement: { type: 'relationship', target: 'goethe', value: 5 }, text: 'Your friendship with Goethe becomes the foundation of your unique approach — science infused with poetry, observation with wonder.', completed: false, reward: { flag: 'goethe_friendship' } },
    ],
  },
  {
    id: 'ocean_currents', title: 'The Ocean\'s Veins', icon: '🌊',
    description: 'Map the great ocean currents that connect the world.',
    currentStage: 0,
    stages: [
      { id: 'ocean_1', title: 'The Cold Current', description: 'Document the current later named after you.', requirement: { type: 'action', target: 'caracas_humboldt_current' }, text: 'You discover the cold current flowing north from Antarctica, bringing life to the desert coast. The "Humboldt Current" will bear your name forever.', completed: false },
    ],
  },
  {
    id: 'magnetic_research', title: 'The Magnetic Web', icon: '🧲',
    description: 'Map the Earth\'s magnetic field across the globe.',
    currentStage: 0,
    stages: [
      { id: 'mag_1', title: 'Magnetic Equator', description: 'Map the line of zero magnetic inclination.', requirement: { type: 'action', target: 'cuba_magnetic' }, text: 'Your precise measurements reveal the magnetic equator — a line where the Earth\'s magnetic field runs parallel to the surface. This work will advance geomagnetism significantly.', completed: false, reward: { flag: 'magnetic_mapped' } },
    ],
  },
  {
    id: 'russia_expedition', title: 'The Final Expedition', icon: '🏔️',
    description: 'At age 60, embark on your last great adventure across Russia.',
    currentStage: 0,
    stages: [
      { id: 'russia_1', title: 'Into the Steppes', description: 'Begin the Russian expedition.', requirement: { type: 'flag', target: 'russia_expedition' }, text: 'Despite your age, you embark on the final great expedition. The vast Russian Empire stretches before you — from the Urals to the Altai Mountains.', completed: false },
      { id: 'russia_2', title: 'Continental Climate', description: 'Compare climates across continents.', requirement: { type: 'data', target: 'data', value: 150 }, text: 'From tropical Venezuela to the frozen steppes, you document how distance from the ocean creates extreme temperature variations. Climate is truly global.', completed: false, reward: { flag: 'climate_global' } },
    ],
  },
  {
    id: 'legacy', title: 'The Legacy', icon: '🌟',
    description: 'Inspire the next generation of scientists.',
    currentStage: 0,
    stages: [
      { id: 'legacy_1', title: 'Mentoring Darwin', description: 'Guide young Charles Darwin.', requirement: { type: 'action', target: 'berlin_legacy' }, text: 'Young Darwin visits, eager for guidance. You encourage him to read your travel narratives. "Go see for yourself," you tell him. He will remember when he boards the Beagle.', completed: false },
      { id: 'legacy_2', title: 'A Living Legacy', description: 'Your ideas spread across the world.', requirement: { type: 'data', target: 'data', value: 200 }, text: 'Your ideas about the interconnectedness of nature spread across the world. Darwin, Thoreau, Muir — they all carry forward your vision. The web of life you described becomes the foundation of ecology.', completed: false, reward: { flag: 'legacy_secured' } },
    ],
  },
  {
    id: 'political_ideals', title: 'Liberty and Contradiction', icon: '⚖️',
    description: 'Navigate the tension between your ideals and reality.',
    currentStage: 0,
    stages: [
      { id: 'pol_1', title: 'The Hypocrisy of Empire', description: 'Document slavery in the colonies.', requirement: { type: 'action', target: 'cuba_slavery' }, text: 'What you witness horrifies you. Enslaved Africans toil under brutal conditions. You document everything — the human cost of colonial wealth. This will fuel your lifelong opposition to slavery.', completed: false },
      { id: 'pol_2', title: 'Revolutionary Ideals', description: 'Support the 1848 revolutions.', requirement: { type: 'action', target: 'berlin_1848' }, text: 'At age 79, you support the revolutionaries from your window. Your liberal ideals conflict with your court position, but your heart is with the people. The old world is changing.', completed: false, reward: { flag: 'revolutionary_spirit' } },
    ],
  },
];

// ===== RELATIONSHIPS =====
export const initialRelationships: Relationship[] = [
  { id: 'bonpland', name: 'Aimé Bonpland', title: 'Companion & Botanist', value: 0, icon: '🌱', description: 'Your partner in exploration. French botanist of extraordinary skill.' },
  { id: 'indigenous', name: 'Indigenous Guides', title: 'Keepers of the Land', value: 0, icon: '🪶', description: 'The peoples who have lived with this land for millennia.' },
  { id: 'scientific_community', name: 'Scientific Community', title: 'Your Peers', value: 0, icon: '🔬', description: 'Fellow scientists across Europe and beyond.' },
  { id: 'goethe', name: 'Johann W. von Goethe', title: 'Poet & Scientist', value: 0, icon: '🪶', description: 'The great writer who taught you to merge art and science.' },
  { id: 'herz', name: 'Henriette Herz', title: 'Salon Hostess', value: 0, icon: '💫', description: 'Intellectual leader of Berlin\'s salon culture.' },
  { id: 'darwin', name: 'Charles Darwin', title: 'Protégé', value: 0, icon: '🐢', description: 'The young naturalist who will carry your legacy forward.' },
];

// ===== STATUS EFFECTS =====
export const statusEffectTemplates = {
  altitude_sickness: {
    id: 'altitude_sickness',
    name: 'Altitude Sickness',
    icon: '🫁',
    description: 'Thin air causes headache, nausea, and difficulty breathing. Humboldt documented this condition during his Chimborazo ascent.',
    severity: 'moderate' as const,
    effects: { vitality: -10, data: -2 },
    duration: 3,
    cure: 'andes_rest',
  },
  hypothermia: {
    id: 'hypothermia',
    name: 'Hypothermia',
    icon: '🥶',
    description: 'Extreme cold saps your strength and clouds your judgment. You must find warmth soon.',
    severity: 'severe' as const,
    effects: { vitality: -15, instruments: -5 },
    duration: 2,
    cure: 'chimborazo_rest',
  },
  tropical_fever: {
    id: 'tropical_fever',
    name: 'Tropical Fever',
    icon: '🤒',
    description: 'A fever wracks your body. The humid air and insect bites have taken their toll.',
    severity: 'moderate' as const,
    effects: { vitality: -12, supplies: -3 },
    duration: 4,
    cure: 'caracas_rest',
  },
  jaguar_wound: {
    id: 'jaguar_wound',
    name: 'Jaguar Wound',
    icon: '🩸',
    description: 'A jaguar attack left you with deep claw marks. The wound needs careful tending.',
    severity: 'severe' as const,
    effects: { vitality: -20, supplies: -5 },
    duration: 5,
    cure: 'llanos_rest',
  },
  electric_shock: {
    id: 'electric_shock',
    name: 'Electric Shock',
    icon: '⚡',
    description: 'An electric eel\'s discharge has left your muscles trembling and your hands numb.',
    severity: 'mild' as const,
    effects: { vitality: -8, instruments: -3 },
    duration: 2,
  },
};

// ===== MORAL DILEMMAS =====
export const moralDilemmas = [
  {
    id: 'tableau_physique',
    title: 'The Tableau Physique Dilemma',
    description: 'While preparing your famous cross-section of Chimborazo, you discover an error in your data. Some plant species were collected from Mt. Antisana, not Chimborazo. You can either:\n\n• Admit the error and delay publication (lose credibility but maintain integrity)\n• Proceed with the elegant but flawed diagram (gain fame but compromise truth)\n• Revise the work extensively (lose time but achieve accuracy)',
    choices: [
      {
        id: 'admit_error',
        text: 'Admit the error publicly',
        effects: { data: -10, vitality: -5 },
        relationship: { id: 'scientific_community', change: -2 },
        flag: 'integrity_maintained',
        outcome: 'You publish a correction, admitting your mistake. Some colleagues question your rigor, but your honesty earns respect from those who value truth over fame. The delay costs you prestige, but your conscience is clear.',
      },
      {
        id: 'proceed_flawed',
        text: 'Proceed with the elegant diagram',
        effects: { data: 15, credits: 20 },
        relationship: { id: 'scientific_community', change: 3 },
        flag: 'fame_over_truth',
        outcome: 'The Tableau Physique becomes a sensation. Your reputation soars as the diagram is praised for its beauty and insight. But you know the truth—some data is from Antisana, not Chimborazo. The weight of this compromise will follow you.',
      },
      {
        id: 'revise_extensively',
        text: 'Revise the work extensively',
        effects: { data: 5, vitality: -10, supplies: -5 },
        flag: 'perfectionist',
        outcome: 'You spend months revising the work, recollecting specimens, and verifying every data point. The final version is accurate but the delay means others publish similar work first. Still, your Tableau Physique stands as a model of scientific rigor.',
      },
    ],
    trigger: { type: 'flag', target: 'chimborazo_ascent_complete', minData: 50 },
  },
  {
    id: 'colonial_compromise',
    title: 'The Colonial Compromise',
    description: 'Spanish colonial officials offer you increased funding and access to restricted areas if you soften your criticism of slavery in your publications. You can:\n\n• Accept their terms (gain resources but betray your principles)\n• Refuse and publish anyway (maintain integrity but lose support)\n• Negotiate a middle ground (partial criticism, partial access)',
    choices: [
      {
        id: 'accept_terms',
        text: 'Accept their terms',
        effects: { credits: 30, instruments: 10 },
        relationship: { id: 'indigenous', change: -5 },
        flag: 'colonial_compromised',
        outcome: 'You gain access to restricted mines and receive generous funding. But when you publish, your criticism of slavery is muted. Bonpland looks at you with disappointment. The indigenous guides you befriended feel betrayed.',
      },
      {
        id: 'refuse_publish',
        text: 'Refuse and publish the truth',
        effects: { credits: -10, vitality: -5 },
        relationship: { id: 'indigenous', change: 3 },
        flag: 'anti_colonial_stance',
        outcome: 'You publish your unvarnished account, condemning slavery and colonial exploitation. The Spanish authorities restrict your access and withdraw support. But your words inspire abolitionists across Europe, and the indigenous peoples remember your courage.',
      },
      {
        id: 'negotiate',
        text: 'Negotiate a middle ground',
        effects: { credits: 15 },
        flag: 'diplomatic_solution',
        outcome: 'You craft a careful compromise—criticizing the system while acknowledging "progress." The officials are satisfied enough to grant limited access. It\'s not the truth you wanted to tell, but it\'s more than you would have managed otherwise. A pragmatic solution, if not a principled one.',
      },
    ],
    trigger: { type: 'location', target: 'mexico', minCycle: 20 },
  },
];

// ===== CORRESPONDENCE TEMPLATES =====
export const correspondenceTemplates = [
  {
    id: 'goethe_letter_1',
    from: 'Johann Wolfgang von Goethe',
    to: 'Alexander von Humboldt',
    subject: 'On the Unity of Nature',
    content: 'My dear Alexander,\n\nYour letters from the Tropics fill me with wonder. You see nature as I have always wished to see it—not as a collection of parts, but as a living whole. Your concept of the "web of life" resonates deeply with my own intuitions about the interconnectedness of all things.\n\nWhen you describe the vegetation zones of Chimborazo, I see not just science but poetry. The mountain is a poem written in the language of nature, and you have learned to read it.\n\nContinue your work, my friend. You are showing the world what I have only glimpsed in my dreams.\n\nYour devoted friend,\nGoethe',
    cycle: 15,
    read: false,
  },
  {
    id: 'darwin_letter_1',
    from: 'Charles Darwin',
    to: 'Alexander von Humboldt',
    subject: 'A Young Naturalist\'s Gratitude',
    content: 'Dear Baron von Humboldt,\n\nI write to you with the deepest respect and gratitude. Your "Personal Narrative" inspired me to pursue natural science, and I carry your words with me as I prepare for my voyage aboard the Beagle.\n\nYou wrote that "the greatest good to the naturalist is to see with his own eyes." I intend to follow your advice. I will observe, collect, and think—though I doubt I shall achieve a fraction of what you have accomplished.\n\nIf I may be so bold, I wonder: do you believe species are fixed, or might they change over time? Your observations of variation in the Tropics must have given you thoughts on this matter.\n\nWith highest admiration,\nCharles Darwin',
    cycle: 40,
    read: false,
  },
  {
    id: 'bonpland_letter_1',
    from: 'Aimé Bonpland',
    to: 'Alexander von Humboldt',
    subject: 'Memories of Our Journey',
    content: 'My dear Alexander,\n\nI think often of our days in the Orinoco, when we collected specimens until our hands were raw and our backs ached. Do you remember the electric eels? We thought we would never escape that pool alive!\n\nThose were the best days of my life. Your vision inspired me, your friendship sustained me. Even now, separated by distance, I feel we are still partners in the great work of understanding nature.\n\nHow fares your great work, Kosmos? I hope it captures even a fraction of the wonder we witnessed together.\n\nYour faithful friend and companion,\nAimé',
    cycle: 30,
    read: false,
  },
];

// ===== WEB OF LIFE CONNECTIONS =====
export const webConnectionTemplates = [
  { from: 'deforestation', to: 'climate_change', strength: 0.9 },
  { from: 'altitude', to: 'temperature', strength: 0.8 },
  { from: 'ocean_currents', to: 'coastal_climate', strength: 0.7 },
  { from: 'volcanic_activity', to: 'soil_fertility', strength: 0.6 },
  { from: 'indigenous_knowledge', to: 'biodiversity', strength: 0.8 },
  { from: 'magnetic_field', to: 'navigation', strength: 0.5 },
  { from: 'vegetation_zones', to: 'animal_migration', strength: 0.7 },
  { from: 'water_cycle', to: 'forest_cover', strength: 0.9 },
];

// ===== BONPLAND ACTIONS =====
export const bonplandActions = {
  bonpland_botanical: {
    id: 'bonpland_botanical',
    name: 'Collaborate with Bonpland on Botany',
    location: 'caracas',
    description: 'Work with your companion to classify the extraordinary plant specimens you\'ve collected.',
    dieRequired: 3,
    skill: 'empathy' as const,
    cost: { supplies: 2 },
    effects: {
      resources: { data: 8 },
      relationship: { id: 'bonpland', change: 2 },
      bonpland: { morale: 5, expertise: 3 },
    },
    successText: 'Bonpland\'s expertise in botany complements your broad vision perfectly. Together you classify dozens of new species, your conversation flowing between scientific precision and shared wonder.',
    failText: 'The work is tedious and the heat oppressive. You and Bonpland make progress, but the pace is slower than hoped.',
    available: true,
  },
  bonpland_morale: {
    id: 'bonpland_morale',
    name: 'Boost Bonpland\'s Spirits',
    location: 'any',
    description: 'Your companion\'s morale is flagging. Spend time encouraging him and reminding him of your shared purpose.',
    dieRequired: 2,
    skill: 'empathy' as const,
    effects: {
      relationship: { id: 'bonpland', change: 3 },
      bonpland: { morale: 15 },
    },
    successText: 'You remind Bonpland of the importance of your work, of the lives that will be touched by your discoveries. His eyes light up with renewed purpose. "You are right, Alexander. We must continue."',
    failText: 'Bonpland appreciates your words, but the hardship has worn him down. He nods politely, but his heart is not yet restored.',
    available: true,
  },
  bonpland_health: {
    id: 'bonpland_health',
    name: 'Care for Bonpland\'s Health',
    location: 'any',
    description: 'Your companion is struggling. Use your knowledge of medicine and your supplies to nurse him back to health.',
    dieRequired: 3,
    skill: 'logic' as const,
    cost: { supplies: 5, instruments: 2 },
    effects: {
      relationship: { id: 'bonpland', change: 2 },
      bonpland: { health: 20 },
    },
    successText: 'Your careful attention and medical knowledge restore Bonpland\'s strength. He rests, eats the nourishing food you prepare, and within days his color returns. "Thank you, my friend," he says.',
    failText: 'You do what you can, but Bonpland\'s condition improves only slightly. He needs more time and better care than you can provide on the trail.',
    available: true,
  },
};

// ===== RANDOM EVENTS =====
export const randomEvents: RandomEvent[] = [
  { id: 'fever', title: 'Tropical Fever', text: 'A sudden fever strikes. You spend days shivering in a hammock, unable to work.', probability: 0.15, minCycle: 3, effects: { vitality: -15, supplies: -5 }, once: true },
  { id: 'storm', title: 'Violent Storm', text: 'A tropical storm batters the expedition. Equipment is damaged, supplies scattered.', probability: 0.12, minCycle: 2, effects: { instruments: -8, supplies: -8 }, once: true },
  { id: 'discovery', title: 'Unexpected Discovery', text: 'While resting, you notice a remarkable specimen you had overlooked. Nature rewards the patient observer.', probability: 0.15, minCycle: 4, effects: { data: 8 } },
  { id: 'supply_cache', title: 'Supply Cache Found', text: 'A previously cached supply depot is found intact. A stroke of luck.', probability: 0.1, minCycle: 5, effects: { supplies: 15 } },
  { id: 'instrument_damage', title: 'Instrument Malfunction', text: 'Your barometer cracks during transport. Precise measurements become more difficult.', probability: 0.1, minCycle: 3, effects: { instruments: -10 } },
  { id: 'kind_stranger', title: 'A Kind Stranger', text: 'A local family offers food and shelter. Their generosity restores your faith in humanity.', probability: 0.12, minCycle: 2, effects: { supplies: 8, vitality: 5 } },
  { id: 'journal_theft', title: 'Notes Damaged', text: 'Humidity has damaged some of your field notes. Irreplaceable observations lost.', probability: 0.08, minCycle: 6, effects: { data: -5 } },
  { id: 'funding', title: 'Royal Funding Arrives', text: 'A shipment of credits from the Crown arrives, along with a letter of encouragement.', probability: 0.1, minCycle: 8, effects: { credits: 20 } },
  { id: 'bonpland_ill', title: 'Bonpland Falls Ill', text: 'Your companion is struck by illness. You must care for him, losing time but gaining closeness.', probability: 0.1, minCycle: 4, effects: { vitality: -5 }, flag: 'cared_for_bonpland', once: true },
  { id: 'moment_of_wonder', title: 'Moment of Wonder', text: 'A sunset of impossible color. A bird of paradise. A flower that glows. Nature reminds you why you began this journey.', probability: 0.2, minCycle: 1, effects: { vitality: 5, data: 2 } },
];

// ===== NATURGEMLÄLDE NODES =====
export const naturgemaldeNodes: NaturgemaldeNode[] = [
  { id: 'tropical_flora', label: 'Tropical Flora', category: 'flora', x: 50, y: 88, connections: ['subtropical_flora', 'insects'], discovered: false },
  { id: 'subtropical_flora', label: 'Subtropical Forest', category: 'flora', x: 35, y: 72, connections: ['temperate_flora', 'tropical_flora'], discovered: false },
  { id: 'temperate_flora', label: 'Temperate Oaks', category: 'flora', x: 42, y: 56, connections: ['alpine_moss', 'subtropical_flora'], discovered: false },
  { id: 'alpine_moss', label: 'Alpine Vegetation', category: 'flora', x: 55, y: 42, connections: ['snow_line', 'temperate_flora'], discovered: false },
  { id: 'snow_line', label: 'Permanent Snow', category: 'climate', x: 50, y: 22, connections: ['alpine_moss', 'atmosphere'], discovered: false },
  { id: 'atmosphere', label: 'Atmospheric Pressure', category: 'climate', x: 78, y: 28, connections: ['snow_line', 'temperature'], discovered: false },
  { id: 'temperature', label: 'Temperature Gradient', category: 'climate', x: 82, y: 52, connections: ['atmosphere', 'geology'], discovered: false },
  { id: 'geology', label: 'Volcanic Geology', category: 'geology', x: 22, y: 48, connections: ['temperature', 'minerals'], discovered: false },
  { id: 'minerals', label: 'Mineral Deposits', category: 'geology', x: 18, y: 72, connections: ['geology', 'insects'], discovered: false },
  { id: 'insects', label: 'Insect Life', category: 'fauna', x: 65, y: 82, connections: ['tropical_flora', 'condors'], discovered: false },
  { id: 'condors', label: 'Andean Condors', category: 'fauna', x: 70, y: 38, connections: ['snow_line', 'insects'], discovered: false },
  { id: 'indigenous', label: 'Indigenous Knowledge', category: 'culture', x: 30, y: 85, connections: ['tropical_flora', 'minerals'], discovered: false },
  { id: 'measurement', label: 'Barometric Data', category: 'measurement', x: 85, y: 70, connections: ['temperature', 'geology'], discovered: false },
];
