import { Location, DialogueNode, JournalEntry, NaturgemaldeNode } from './types';

// ===== LOCATIONS =====
export const locations: Record<string, Location> = {
  berlin: {
    id: 'berlin',
    name: 'Berlin, Prussia',
    region: 'Europe',
    description: 'The grand capital of Prussia. Salons buzz with Enlightenment discourse. You stand at a crossroads — your mother has recently passed, leaving you an inheritance and the freedom to pursue your lifelong dream of exploration.',
    atmosphere: 'Intellectual salons, candlelit libraries, the weight of possibility.',
    connections: ['caracas'],
    dialogues: ['berlin_saloon', 'berlin_wilhelm'],
    events: ['berlin_prepare'],
    journalData: 'european_foundation',
  },
  caracas: {
    id: 'caracas',
    name: 'Caracas, Venezuela',
    region: 'South America',
    description: 'The warm Caribbean air greets you as you step ashore. The Captaincy General of Venezuela stretches before you — a land of dramatic contrasts, from coastal cities to vast interior plains. Your instruments are ready. The expedition begins.',
    atmosphere: 'Tropical heat, colonial architecture, the scent of unfamiliar flowers.',
    connections: ['berlin', 'llanos', 'lake_valencia'],
    dialogues: ['caracas_bonpland'],
    events: ['caracas_arrival'],
    journalData: 'venezuela_arrival',
  },
  llanos: {
    id: 'llanos',
    name: 'The Venezuelan Llanos',
    region: 'South America',
    description: 'Vast, treeless plains extend to the horizon. The grasslands are home to wild horses, capybaras, and the llaneros — rough horsemen who live by their own code. Supplies are scarce, and the sun is merciless.',
    atmosphere: 'Endless grass, blazing sun, the thunder of hooves on hard earth.',
    connections: ['caracas', 'orinoco'],
    dialogues: ['llanos_llanero'],
    events: ['llanos_survival', 'llanos_jaguars'],
    journalData: 'llanos_ecosystem',
  },
  lake_valencia: {
    id: 'lake_valencia',
    name: 'Lake Valencia',
    region: 'South America',
    description: 'Once a great body of water, the lake has been receding alarmingly. You notice the connection — vast areas of forest have been cleared for agriculture upstream. The water cycle itself seems altered.',
    atmosphere: 'Shallow waters, exposed mudflats, stumps of felled trees.',
    connections: ['caracas', 'llanos'],
    dialogues: ['valencia_farmer'],
    events: ['valencia_investigation'],
    journalData: 'deforestation_climate',
  },
  orinoco: {
    id: 'orinoco',
    name: 'The Orinoco River',
    region: 'South America',
    description: 'The great river winds through dense jungle. Its waters teem with life — and danger. You have heard reports of electric eels of extraordinary power in these tributaries. The indigenous peoples know these waters well.',
    atmosphere: 'Dark waters, cacophony of jungle sounds, humidity that clings like a second skin.',
    connections: ['llanos', 'andes_foothills'],
    dialogues: ['orinoco_indigenous'],
    events: ['orinoco_eels', 'orinoco_navigation'],
    journalData: 'orinoco_biodiversity',
  },
  andes_foothills: {
    id: 'andes_foothills',
    name: 'Andes Foothills',
    region: 'South America',
    description: 'The great mountain chain rises before you. The air grows cooler with each step upward. Vegetation changes dramatically with altitude — from tropical lowland species to temperate forests to alpine tundra. Your barometer confirms the thinning atmosphere.',
    atmosphere: 'Cool mountain air, changing vegetation belts, the call of condors.',
    connections: ['orinoco', 'chimborazo'],
    dialogues: ['andes_guide'],
    events: ['andes_vegetation', 'andes_barometer'],
    journalData: 'altitudinal_zonation',
  },
  chimborazo: {
    id: 'chimborazo',
    name: 'Chimborazo Summit',
    region: 'Ecuador',
    description: 'The great volcano towers above all. At 19,286 feet, it was believed to be the highest peak in the world. The air is thin, the cold biting. Every breath is a struggle. But the view — the view will change how humanity understands nature itself.',
    atmosphere: 'Crystalline air, vertiginous heights, the curvature of the Earth visible on the horizon.',
    connections: ['andes_foothills', 'mexico'],
    dialogues: ['chimborazo_bonpland'],
    events: ['chimborazo_ascent', 'chimborazo_naturgemalde'],
    requiredFlag: 'reached_andes',
    journalData: 'chimborazo_summit',
  },
  mexico: {
    id: 'mexico',
    name: 'New Spain (Mexico)',
    region: 'North America',
    description: 'The Viceroyalty of New Spain is a land of immense wealth and deep inequality. Silver mines pour riches into Spanish coffers while indigenous laborers toil in darkness. Your surveying instruments will chart this land with unprecedented precision.',
    atmosphere: 'Colonial grandeur, silver and stone, the tension between old world and new.',
    connections: ['chimborazo', 'europe_return'],
    dialogues: ['mexico_jefferson', 'mexico_mine'],
    events: ['mexico_survey', 'mexico_mine_analysis'],
    journalData: 'new_spain_economy',
  },
  europe_return: {
    id: 'europe_return',
    name: 'Paris, France',
    region: 'Europe',
    description: 'You return to Europe after nearly five years of extraordinary travel. Your collections, notes, and observations fill dozens of crates. Now begins the great work of synthesis — transforming raw data into a unified vision of nature. Your masterwork, Kosmos, awaits.',
    atmosphere: 'Scholarly intensity, the weight of accumulated knowledge, the dawn of a new understanding.',
    connections: ['mexico'],
    dialogues: ['paris_goethe', 'paris_darwin'],
    events: ['paris_publication', 'paris_kosmos'],
    journalData: 'cosmos_synthesis',
  },
};

// ===== DIALOGUES =====
export const dialogues: Record<string, DialogueNode> = {
  berlin_saloon: {
    id: 'berlin_saloon',
    speaker: 'Henriette Herz',
    text: 'Ah, Herr von Humboldt! We were just discussing Kant\'s latest Critique. Your mother\'s passing must weigh heavily upon you. But I see that fire in your eyes — the same fire that has always drawn you toward the unknown. Tell me, what will you do with this... freedom?',
    options: [
      {
        id: 'logic_response',
        text: '"I intend to apply the rigorous methods of natural philosophy to the unexplored regions of the New World. Systematic observation is the key to understanding nature\'s laws."',
        skill: 'logic',
        skillRequired: 3,
        successText: 'Henriette nods approvingly. "Methodical as ever, Alexander. Kant himself would approve. Your instruments are your compass — let them guide you where intuition cannot."',
        effects: { resources: { morale: 5 }, journal: 'kant_methodology' },
      },
      {
        id: 'aesthetic_response',
        text: '"I feel it in my bones — there is a beauty in nature that science has yet to capture. I want to see the Tropics, to feel the totality of life in a single landscape."',
        skill: 'aesthetics',
        skillRequired: 3,
        successText: 'Henriette\'s eyes light up. "A poet-scientist! How wonderful. Goethe would love you, I think. Remember — the eye sees what the mind is prepared to comprehend."',
        effects: { resources: { morale: 8 }, journal: 'romantic_vision' },
      },
      {
        id: 'political_response',
        text: '"I will observe not just nature, but the societies that inhabit it. The Spanish colonies... I have questions about the justice of their rule."',
        skill: 'political',
        skillRequired: 3,
        successText: 'Henriette lowers her voice. "Careful, Alexander. Such thoughts are dangerous even here. But you are right — the Enlightenment must extend to all peoples, or it is nothing."',
        effects: { resources: { morale: 3 }, flag: 'political_awareness' },
      },
      {
        id: 'simple_response',
        text: '"I am not yet sure. But I know I must go. The New World calls to me."',
        successText: 'Henriette smiles gently. "Then go with our blessings. The salon will miss you, but the world will benefit from your journey."',
        effects: { resources: { morale: 2 } },
      },
      {
        id: 'exit',
        text: '[Leave the salon]',
        isExit: true,
      },
    ],
  },
  berlin_wilhelm: {
    id: 'berlin_wilhelm',
    speaker: 'Wilhelm von Humboldt (Brother)',
    text: 'Alexander. I have been thinking about our childhood debates — how you always wanted to dissect the butterfly while I wanted to understand the language it spoke. Perhaps we are not so different. Both of us seeking to understand the whole through its parts.',
    options: [
      {
        id: 'brother_logic',
        text: '"You study the structure of language itself — the grammar of human thought. I study the grammar of nature. We are both linguists, Wilhelm."',
        skill: 'logic',
        skillRequired: 4,
        successText: 'Wilhelm laughs. "A linguist of nature! I like that. Perhaps someday we will find the universal grammar that connects both our fields — the deep structure of all knowledge."',
        effects: { resources: { morale: 10 }, journal: 'brother_bond' },
      },
      {
        id: 'brother_empathy',
        text: '"I will miss you, brother. This journey... it may be years. Perhaps forever. But your letters will be my anchor."',
        skill: 'empathy',
        skillRequired: 3,
        successText: 'Wilhelm\'s eyes glisten. "And mine will be yours. Whatever you discover, whatever you become — remember that you have a home here. Write to me. Promise me."',
        effects: { resources: { morale: 12 }, flag: 'wilhelm_promise' },
      },
      {
        id: 'exit',
        text: '[Embrace your brother and depart]',
        isExit: true,
      },
    ],
  },
  caracas_bonpland: {
    id: 'caracas_bonpland',
    speaker: 'Aimé Bonpland',
    text: 'Mon ami! We made it! Look at these specimens — I have already identified three species unknown to European science, and we have been ashore for less than a day! The botanical wealth here is... incomprehensible. Where shall we begin?',
    options: [
      {
        id: 'bonpland_logic',
        text: '"We must be systematic. I will calibrate the instruments first — barometer, thermometer, the eudiometer. Precise measurements before collection."',
        skill: 'logic',
        skillRequired: 3,
        successText: 'Bonpland grins. "Always the engineer! Very well — while you calibrate, I will begin pressing specimens. Together, measurement and collection. The perfect partnership."',
        effects: { resources: { data: 5 }, journal: 'instrument_calibration' },
      },
      {
        id: 'bonpland_empathy',
        text: '"First, we find a local guide who knows this land. The indigenous peoples have centuries of knowledge we would be foolish to ignore."',
        skill: 'empathy',
        skillRequired: 4,
        successText: 'Bonpland nods thoughtfully. "You are right, as always. Science without respect for those who have lived with this land for millennia... that would be a different kind of colonialism."',
        effects: { resources: { morale: 5, supplies: -3 }, flag: 'indigenous_respect', journal: 'local_knowledge' },
      },
      {
        id: 'bonpland_aesthetic',
        text: '"Look at that mountain, Aimé! The way the clouds wrap around its peak like a living thing. We must climb it. Whatever it takes."',
        skill: 'aesthetics',
        skillRequired: 3,
        successText: 'Bonpland follows your gaze and his face transforms. "Magnifique... You see it too, don\'t you? Not just a mountain, but a world stacked upon itself. Every altitude a different country."',
        effects: { resources: { morale: 8 }, journal: 'mountain_vision' },
      },
      {
        id: 'exit',
        text: '[Plan the route inland]',
        isExit: true,
      },
    ],
  },
  llanos_llanero: {
    id: 'llanos_llanero',
    speaker: 'A Llanero Herdsman',
    text: 'You Europeans always come with your strange boxes and glass eyes. The plains have been here since before your kings drew lines on maps. What do you seek in this land of grass and wind?',
    options: [
      {
        id: 'llanero_empathy',
        text: '"I seek understanding, not conquest. Your knowledge of these plains is greater than any book. Will you teach me what the land has taught you?"',
        skill: 'empathy',
        skillRequired: 4,
        successText: 'The herdsman studies you for a long moment, then nods slowly. "You are different from the others. Come — I will show you where the water hides beneath the dry season, and when the fish run in the flooded savanna."',
        effects: { resources: { supplies: 10, morale: 8 }, flag: 'llanero_ally', journal: 'llanero_knowledge' },
      },
      {
        id: 'llanero_logic',
        text: '"I measure the world so that all people might understand it. These plains hold secrets about climate, about how forests and rivers connect across continents."',
        skill: 'logic',
        skillRequired: 3,
        successText: '"Secrets, eh? The plains have no secrets — they show everything to those who watch. But your glass eyes... perhaps they see what my old eyes cannot. Very well."',
        effects: { resources: { data: 5 }, journal: 'llanos_measurement' },
      },
      {
        id: 'llanero_political',
        text: '"I have seen the Spanish treatment of indigenous peoples. I do not approve. I believe all men are equal under nature\'s law."',
        skill: 'political',
        skillRequired: 4,
        successText: 'The herdsman\'s eyes narrow, then soften. "Words are wind, señor. But you speak differently. Perhaps... perhaps there is hope yet from the old world."',
        effects: { resources: { morale: 5 }, flag: 'anti_colonial', journal: 'colonial_critique' },
      },
      {
        id: 'exit',
        text: '[Continue across the plains]',
        isExit: true,
      },
    ],
  },
  valencia_farmer: {
    id: 'valencia_farmer',
    speaker: 'A Local Farmer',
    text: 'The lake shrinks more every year, señor. My grandfather told stories of boats that could sail where now only cattle graze. The forests are gone — cut for firewood, for fields, for timber. And the rains... they come less often now.',
    options: [
      {
        id: 'valencia_logic',
        text: '"The connection is clear — deforestation reduces transpiration, which reduces rainfall. The trees and the lake are part of a single system. I must document this."',
        skill: 'logic',
        skillRequired: 4,
        successText: 'You spend hours taking measurements — humidity, temperature, soil moisture. The data confirms your hypothesis: human activity is altering the climate itself. This is a discovery that will shock the scientific world.',
        effects: { resources: { data: 15 }, journal: 'climate_change_discovery' },
      },
      {
        id: 'valencia_aesthetic',
        text: '"There is a tragedy here that numbers alone cannot capture. The destruction of a landscape is the destruction of a living poem. I will make them see it."',
        skill: 'aesthetics',
        skillRequired: 3,
        successText: 'You sketch the barren landscape, the exposed lakebed, the stumps. Your drawing captures something data cannot — the grief of a wounded earth. This will become one of your most powerful illustrations.',
        effects: { resources: { data: 8, morale: -3 }, journal: 'landscape_grief' },
      },
      {
        id: 'exit',
        text: '[Record your observations and move on]',
        isExit: true,
      },
    ],
  },
  orinoco_indigenous: {
    id: 'orinoco_indigenous',
    speaker: 'An Indigenous Guide',
    text: 'The river has its own spirit, stranger. The eels you seek — we call them the thunder-fish. They guard the deep pools. To catch one, you must understand that the river gives and takes in equal measure.',
    options: [
      {
        id: 'indigenous_empathy',
        text: '"I do not wish to conquer the river. I wish to learn from it. Teach me your ways of reading the water, and I will share what my instruments reveal."',
        skill: 'empathy',
        skillRequired: 5,
        successText: 'The guide\'s face breaks into a rare smile. "You listen. That is rare for your kind. Come — I will show you where the thunder-fish gather, and you will learn that knowledge flows in many channels."',
        effects: { resources: { supplies: 5, morale: 10, data: 8 }, flag: 'river_knowledge', journal: 'indigenous_ecology' },
      },
      {
        id: 'indigenous_logic',
        text: '"My instruments can measure the electrical discharge of these creatures. Understanding their power could advance human knowledge of electricity itself."',
        skill: 'logic',
        skillRequired: 4,
        successText: 'The guide watches as you set up your equipment with careful precision. "Your glass and metal eyes see differently than mine. Perhaps both visions are needed to understand the thunder-fish."',
        effects: { resources: { data: 12 }, journal: 'electric_eel_research' },
      },
      {
        id: 'exit',
        text: '[Thank the guide and continue downriver]',
        isExit: true,
      },
    ],
  },
  andes_guide: {
    id: 'andes_guide',
    speaker: 'A Mountain Guide',
    text: 'The mountain does not welcome strangers, señor. Each level you climb strips away something — warmth, breath, certainty. The plants know this. They change their very nature as they ascend. What you seek at the top... many have died seeking it.',
    options: [
      {
        id: 'guide_aesthetic',
        text: '"I see it already — the vegetation belts, each one a different world stacked upon the last. It is like reading the layers of a great painting. I must see the whole canvas."',
        skill: 'aesthetics',
        skillRequired: 4,
        successText: 'The guide pauses, then looks at the mountain with new eyes. "You see it as I do... not as a barrier, but as a story told in stone and leaf. Very well. I will take you as high as the mountain allows."',
        effects: { resources: { morale: 10 }, flag: 'reached_andes', journal: 'mountain_painting' },
      },
      {
        id: 'guide_logic',
        text: '"I have measured the barometric pressure at each altitude. The data shows a clear pattern — I can predict where the danger zones lie. Science will keep us alive."',
        skill: 'logic',
        skillRequired: 5,
        successText: 'The guide examines your charts with growing respect. "Your numbers... they match what my grandfather told me in stories. The mountain speaks in your language too. I will guide you."',
        effects: { resources: { data: 10, health: 5 }, flag: 'reached_andes', journal: 'altitude_science' },
      },
      {
        id: 'guide_simple',
        text: '"I must try. Whatever the cost. The summit holds answers that the world needs."',
        successText: 'The guide sighs. "Many have said such things. But your eyes... they are different. Perhaps you will survive where others failed. We leave at dawn."',
        effects: { resources: { morale: 5 }, flag: 'reached_andes' },
      },
      {
        id: 'exit',
        text: '[Prepare for the ascent]',
        isExit: true,
      },
    ],
  },
  chimborazo_bonpland: {
    id: 'chimborazo_bonpland',
    speaker: 'Aimé Bonpland (at altitude)',
    text: 'Alexander... my friend... I can barely breathe. The cold... it cuts through everything. But look — look at the layers below us. Every hundred feet, a different world. Tropical forest gave way to oak, then pine, then moss, then nothing but ice and sky. It is... it is everything we theorized, made real.',
    options: [
      {
        id: 'chimborzo_aesthetic',
        text: '"This is it, Aimé. This is the painting of nature itself. Every zone a brushstroke. I can see it all — from the tropical lowlands to the eternal ice — as one single, unified composition."',
        skill: 'aesthetics',
        skillRequired: 5,
        successText: 'Bonpland grips your arm, his breath coming in ragged gasps. "Then paint it, Alexander. Paint it for the world. Let them see what we see — the whole mountain as one living organism." Your hands shake, but your vision is crystal clear.',
        effects: { resources: { data: 20, morale: 15 }, journal: 'naturgemalde_vision' },
      },
      {
        id: 'chimborzo_logic',
        text: '"Record everything. Temperature at each zone. The species boundaries. The barometric readings. This data will prove that nature operates by universal laws — the same forces from equator to pole."',
        skill: 'logic',
        skillRequired: 5,
        successText: 'You pull out your notebook with frozen fingers. Every number is precious. The thermometer reads lower than any ever recorded at this altitude. This is data that will rewrite the textbooks of every science.',
        effects: { resources: { data: 25, health: -10 }, journal: 'extreme_data' },
      },
      {
        id: 'chimborzo_empathy',
        text: '"Hold on, Aimé. We will descend soon. No discovery is worth your life. You are more important than any mountain."',
        skill: 'empathy',
        skillRequired: 4,
        successText: 'Bonpland squeezes your hand. "You always see the human cost, Alexander. It is why you are great — not just the measurements, but the heart behind them. Let us go down together."',
        effects: { resources: { morale: 15, health: 5 }, journal: 'friendship_summit' },
      },
      {
        id: 'exit',
        text: '[Begin the careful descent]',
        isExit: true,
      },
    ],
  },
  mexico_jefferson: {
    id: 'mexico_jefferson',
    speaker: 'President Thomas Jefferson',
    text: 'Baron von Humboldt! Your reputation precedes you across the Atlantic. I understand you have mapped territories of New Spain that we know almost nothing about — the lands west of the Mississippi. My country is... eager to learn more about these regions.',
    options: [
      {
        id: 'jefferson_political',
        text: '"Mr. President, I will share my geographic data freely — knowledge belongs to all humanity. But I must note: the same ideals of liberty you champion are denied to millions held in bondage. This contradiction troubles me deeply."',
        skill: 'political',
        skillRequired: 5,
        successText: 'Jefferson\'s smile fades, then returns, thinner. "You are blunt, Baron. Perhaps too blunt for diplomacy. But... perhaps that is exactly what a man in my position needs to hear. The maps, if you would?"',
        effects: { resources: { morale: 10, data: 5 }, flag: 'jefferson_slavery', journal: 'liberty_contradiction' },
      },
      {
        id: 'jefferson_logic',
        text: '"I have prepared detailed charts of elevation, mineral deposits, and river systems. The data speaks for itself — this territory is far richer and more complex than anyone in Europe has imagined."',
        skill: 'logic',
        skillRequired: 4,
        successText: 'Jefferson leans forward, eyes alight. "Extraordinary. This changes everything we thought we knew about the West. You have given my country an invaluable gift, Baron."',
        effects: { resources: { data: 15, morale: 5 }, journal: 'geographic_diplomacy' },
      },
      {
        id: 'exit',
        text: '[Conclude the diplomatic meeting]',
        isExit: true,
      },
    ],
  },
  mexico_mine: {
    id: 'mexico_mine',
    speaker: 'A Mine Overseer',
    text: 'The Valenciana mine produces more silver than any other in the world, señor. But the cost... the indigenous miners die by the hundreds. Cave-ins, mercury poisoning, collapsed lungs. The wealth of New Spain is measured in their blood.',
    options: [
      {
        id: 'mine_political',
        text: '"This is an outrage. I will document everything — the production figures AND the human cost. The world must know that \'progress\' built on suffering is no progress at all."',
        skill: 'political',
        skillRequired: 4,
        successText: 'The overseer looks nervous. "You are a brave man, señor. Or a foolish one. Either way — the records are there. Take them. Perhaps the old world needs to see what the new world truly costs."',
        effects: { resources: { data: 10, morale: -5 }, flag: 'mine_documentation', journal: 'mining_exploitation' },
      },
      {
        id: 'mine_logic',
        text: '"I need to survey the geological formations, calculate the ore yields, and map the mine\'s full extent. Understanding the geology may lead to safer extraction methods."',
        skill: 'logic',
        skillRequired: 4,
        successText: 'You spend three days in the mine, measuring, mapping, calculating. Your geological survey reveals rich deposits previously unknown — and ventilation shafts that could save lives.',
        effects: { resources: { data: 15, health: -8 }, journal: 'mine_geology' },
      },
      {
        id: 'exit',
        text: '[Leave the mine with your observations]',
        isExit: true,
      },
    ],
  },
  paris_goethe: {
    id: 'paris_goethe',
    speaker: 'Johann Wolfgang von Goethe',
    text: 'Alexander! My dear friend! I have read your accounts of the Tropics and I wept — not from sadness, but from recognition. You have shown me what I always felt but could not express: that nature is not a mechanism but a poem. That science and art are the same impulse, seen through different lenses.',
    options: [
      {
        id: 'goethe_aesthetic',
        text: '"Johann, you taught me to see. Before you, I was merely measuring. Now I understand that every number tells a story, every data point is a brushstroke in nature\'s great painting."',
        skill: 'aesthetics',
        skillRequired: 5,
        successText: 'Goethe embraces you. "And you have taught me that the poem has structure, that beauty has law. Together, we have bridged the great divide. This is our legacy, Alexander — the unity of knowledge."',
        effects: { resources: { morale: 20, data: 10 }, journal: 'goethe_synthesis' },
      },
      {
        id: 'goethe_empathy',
        text: '"My friend, these years apart have been the hardest of my life. Your letters sustained me. Now, at last, we can work together — not through ink on paper, but side by side."',
        skill: 'empathy',
        skillRequired: 4,
        successText: 'Goethe\'s eyes are bright. "And so we shall. The world is ready for what we have to offer — a vision of nature that speaks to both the head and the heart. Come, let us begin."',
        effects: { resources: { morale: 15 }, flag: 'goethe_friendship', journal: 'friendship_renewed' },
      },
      {
        id: 'exit',
        text: '[Sit down together to plan your masterwork]',
        isExit: true,
      },
    ],
  },
  paris_darwin: {
    id: 'paris_darwin',
    speaker: 'A Young Charles Darwin',
    text: 'Baron von Humboldt... I read your narrative of travel as a boy and it changed the course of my life. I am preparing for a voyage of my own — aboard the Beagle, to South America. I wanted to thank you. You showed me that one person, with patience and observation, could understand the world.',
    options: [
      {
        id: 'darwin_empathy',
        text: '"Young man, the greatest gift a scientist can give is not data, but inspiration. If my work has kindled that fire in you, then my life\'s purpose is fulfilled. Go — and see with your own eyes."',
        skill: 'empathy',
        skillRequired: 4,
        successText: 'Darwin\'s eyes shine with determination. "I will, Baron. I promise you — I will carry forward what you began. The web of life you described... I believe I may find new threads in it."',
        effects: { resources: { morale: 20 }, flag: 'darwin_mentored', journal: 'darwin_legacy' },
      },
      {
        id: 'darwin_logic',
        text: '"Take careful measurements. Document everything. But remember — the data alone is not enough. You must seek the connections, the hidden patterns that link all living things."',
        skill: 'logic',
        skillRequired: 4,
        successText: 'Darwin nods eagerly, pulling out a notebook. "Yes, Baron! The connections — that is what fascinates me most. How species change, how they adapt... there must be a law behind it all."',
        effects: { resources: { data: 5, morale: 10 }, journal: 'darwin_method' },
      },
      {
        id: 'exit',
        text: '[Watch the young naturalist depart, filled with hope for the future]',
        isExit: true,
      },
    ],
  },
};

// ===== EVENTS =====
export const events: Record<string, import('./types').GameEvent> = {
  berlin_prepare: {
    id: 'berlin_prepare',
    title: 'Preparing for Expedition',
    description: 'You must carefully select which of your 42 scientific instruments to bring. Each adds weight but provides unique capabilities. The ship has limited cargo space.',
    skill: 'logic',
    difficulty: 3,
    successText: 'Your careful selection proves wise. Every instrument finds its purpose in the field. The barometer will be crucial in the mountains; the eudiometer in the jungles.',
    failText: 'You packed too hastily. Several instruments were damaged in transit, and you lack key tools for high-altitude measurement.',
    successEffects: { data: 10, supplies: -5 },
    failEffects: { data: -5, supplies: -3 },
    journal: 'instrument_selection',
  },
  caracas_arrival: {
    id: 'caracas_arrival',
    title: 'First Steps in the New World',
    description: 'The tropical heat is overwhelming after months at sea. You must acclimate quickly — there is much to observe and the climate will not wait.',
    skill: 'logic',
    difficulty: 2,
    successText: 'Your systematic approach to acclimatization pays off. Within days, you are taking measurements with precision despite the oppressive heat.',
    failText: 'The heat takes its toll. You lose several days to fever before recovering. Valuable time is lost.',
    successEffects: { data: 5, health: 5 },
    failEffects: { health: -15, supplies: -5 },
    journal: 'tropical_acclimation',
  },
  llanos_survival: {
    id: 'llanos_survival',
    title: 'Surviving the Llanos',
    description: 'The plains offer little shelter from the sun. Water sources are scarce and unpredictable. Your supplies dwindle with each passing day.',
    skill: 'logic',
    difficulty: 4,
    successText: 'Your knowledge of hydrology helps you locate underground water sources. The llaneros watch with approval as you read the land like a book.',
    failText: 'Days without water weaken you terribly. Bonpland falls ill. You must press on despite growing desperation.',
    successEffects: { supplies: 10, health: 5 },
    failEffects: { supplies: -15, health: -15 },
    journal: 'llanos_water',
  },
  llanos_jaguars: {
    id: 'llanos_jaguars',
    title: 'Jaguar Encounter',
    description: 'At night, the eyes of jaguars gleam at the edge of your camp. These apex predators are bold and unafraid. One wrong move could be fatal.',
    skill: 'empathy',
    difficulty: 4,
    successText: 'Your calm, respectful demeanor seems to communicate to the jaguar that you are not prey. It watches for a long moment, then melts back into the darkness.',
    failText: 'The jaguar charges! You barely escape with your life, but supplies are scattered and morale plummets.',
    successEffects: { morale: 10, data: 5 },
    failEffects: { health: -20, supplies: -10, morale: -10 },
    journal: 'jaguar_encounter',
  },
  valencia_investigation: {
    id: 'valencia_investigation',
    title: 'Investigating Lake Valencia',
    description: 'You set up a series of measurements around the shrinking lake — water levels, temperature, humidity, soil composition. The pattern is becoming clear.',
    skill: 'logic',
    difficulty: 4,
    successText: 'Your data is conclusive: deforestation has altered the local water cycle. This is one of the first documented cases of human-induced climate change.',
    failText: 'Your measurements are inconclusive — too many variables, too little time. The pattern eludes you for now.',
    successEffects: { data: 20 },
    failEffects: { data: 3 },
    journal: 'lake_valencia_data',
  },
  orinoco_eels: {
    id: 'orinoco_eels',
    title: 'The Electric Eel Expedition',
    description: 'The indigenous people have agreed to help you capture electric eels — but the method is dangerous. They will drive wild horses into the pool to provoke the eels into discharging their energy.',
    skill: 'empathy',
    difficulty: 5,
    successText: 'You witness the extraordinary spectacle — the eels, exhausted after their electrical battle with the horses, can now be safely collected. Your measurements reveal the most powerful bioelectricity known to science.',
    failText: 'The process is more violent than expected. You receive a painful shock that leaves your hand numb for days. Some specimens are lost.',
    successEffects: { data: 15, health: -5 },
    failEffects: { health: -15, data: 3 },
    journal: 'electric_eels',
  },
  orinoco_navigation: {
    id: 'orinoco_navigation',
    title: 'Navigating the Orinoco',
    description: 'The river branches endlessly. Without accurate charts, you could sail for weeks without finding your way. Your astronomical instruments are your only guide.',
    skill: 'logic',
    difficulty: 4,
    successText: 'Your celestial navigation is flawless. You map the river\'s course with unprecedented accuracy, connecting the Orinoco to the Amazon through the Casiquiare channel.',
    failText: 'Cloud cover prevents astronomical observations for days. You wander in circles, burning precious supplies.',
    successEffects: { data: 15, supplies: -3 },
    failEffects: { supplies: -12, morale: -5 },
    journal: 'orinoco_mapping',
  },
  andes_vegetation: {
    id: 'andes_vegetation',
    title: 'Documenting Vegetation Zones',
    description: 'Every hundred meters of altitude brings a completely different ecosystem. You must catalog each zone — the species, their boundaries, the transitions between them.',
    skill: 'aesthetics',
    difficulty: 4,
    successText: 'Your artistic eye captures what pure science would miss — the aesthetic logic of nature\'s zonation. Each belt is not just different species, but a different character, a different mood.',
    failText: 'You struggle to capture the subtle transitions between zones. The boundaries blur, and your notes feel inadequate to the reality.',
    successEffects: { data: 15, morale: 5 },
    failEffects: { data: 5 },
    journal: 'vegetation_zones',
  },
  andes_barometer: {
    id: 'andes_barometer',
    title: 'High-Altitude Barometry',
    description: 'Your barometer is your most precious instrument at altitude. Each reading tells you about the thinning atmosphere, the decreasing pressure, the changing nature of the air itself.',
    skill: 'logic',
    difficulty: 5,
    successText: 'Your measurements at extreme altitude are flawless. The data reveals the precise mathematical relationship between altitude and atmospheric pressure — a formula that will be used for centuries.',
    failText: 'The cold makes your fingers clumsy. The barometer\'s mercury contracts unpredictably. Your readings at the highest points are unreliable.',
    successEffects: { data: 20 },
    failEffects: { data: 5, health: -5 },
    journal: 'barometric_formula',
  },
  chimborazo_ascent: {
    id: 'chimborazo_ascent',
    title: 'The Final Ascent',
    description: 'The summit attempt. Every step is agony. The air is so thin that each breath barely sustains you. Ice coats your instruments. Bonpland struggles beside you. This is the moment everything has led to.',
    skill: 'logic',
    difficulty: 6,
    successText: 'Through sheer determination and scientific precision, you reach a record altitude of 19,286 feet. You are higher than any human has ever been. The world unfolds below you — and you understand it all.',
    failText: 'Altitude sickness overwhelms you. You must turn back 500 feet below the summit, gasping and bleeding from the nose. The dream remains unfulfilled.',
    successEffects: { data: 30, health: -20, morale: 20 },
    failEffects: { health: -25, morale: -15 },
    journal: 'chimborazo_record',
    flag: 'summit_attempted',
  },
  chimborazo_naturgemalde: {
    id: 'chimborazo_naturgemalde',
    title: 'Creating the Naturgemälde',
    description: 'Now you must synthesize everything — all your data, observations, and artistic vision — into a single diagram that shows the mountain as a living whole. This is your masterwork.',
    skill: 'aesthetics',
    difficulty: 6,
    successText: 'The Naturgemälde takes shape — a cross-section of Chimborazo showing vegetation zones, geological strata, atmospheric data, and the interconnected web of life from base to summit. It is beautiful. It is true. It will change how humanity sees nature.',
    failText: 'The synthesis eludes you. Too much data, too many observations — you cannot find the unifying vision. The diagram remains incomplete, a collection of fragments rather than a whole.',
    successEffects: { data: 25, morale: 25 },
    failEffects: { morale: -10, data: 5 },
    journal: 'naturgemalde_complete',
    flag: 'naturgemalde_created',
  },
  mexico_survey: {
    id: 'mexico_survey',
    title: 'Surveying New Spain',
    description: 'You chart the road from Acapulco to Mexico City, measuring every change in elevation, noting every geological formation, cataloging every species along the route.',
    skill: 'logic',
    difficulty: 4,
    successText: 'Your survey is the most detailed map of Mexican territory ever produced. Elevation profiles, mineral deposits, vegetation zones — all rendered with exquisite precision.',
    failText: 'The terrain is more complex than expected. Your survey is incomplete, with gaps in the mountainous regions.',
    successEffects: { data: 15 },
    failEffects: { data: 5, supplies: -5 },
    journal: 'mexico_survey_complete',
  },
  mexico_mine_analysis: {
    id: 'mexico_mine_analysis',
    title: 'Analyzing the Valenciana Mine',
    description: 'Three days in the silver mine. The darkness, the heat, the danger — and the incredible wealth flowing through these tunnels. You must document both the geology and the economics.',
    skill: 'political',
    difficulty: 5,
    successText: 'Your analysis reveals the full picture — the geological richness, the economic system, and the human cost. This balanced account will become a landmark in political economy.',
    failText: 'The mine overwhelms you. The darkness, the suffering of the miners — you cannot maintain the objectivity needed for proper analysis.',
    successEffects: { data: 15, morale: -5 },
    failEffects: { data: 3, morale: -10 },
    journal: 'mine_full_analysis',
  },
  paris_publication: {
    id: 'paris_publication',
    title: 'Publishing Your Life\'s Work',
    description: 'Twenty years of work distilled into thirty volumes. The Voyage to the Equinoctial Regions is the most ambitious scientific publication ever attempted. Every illustration, every table, every word must be perfect.',
    skill: 'logic',
    difficulty: 5,
    successText: 'The publication is a triumph. Scientists across Europe hail it as a masterpiece of observation and synthesis. Your name becomes synonymous with exploration itself.',
    failText: 'The sheer volume of material proves overwhelming. Publication is delayed, and some sections remain incomplete.',
    successEffects: { data: 20, morale: 15 },
    failEffects: { morale: -10 },
    journal: 'voyage_published',
  },
  paris_kosmos: {
    id: 'paris_kosmos',
    title: 'Writing Kosmos',
    description: 'Your final and greatest work — an attempt to unify all of nature into a single vision. Everything you have observed, measured, and felt must be woven into one coherent tapestry of understanding.',
    skill: 'aesthetics',
    difficulty: 7,
    successText: 'Kosmos is complete. Five volumes that unite astronomy and geography, physics and poetry, data and beauty. You have shown the world that nature is not a collection of parts but a living, breathing whole. Your life\'s work is done.',
    failText: 'The synthesis remains incomplete. The threads of knowledge are too many, too complex. Kosmos remains a fragment of the vision you carried.',
    successEffects: { data: 30, morale: 30 },
    failEffects: { morale: -5 },
    journal: 'kosmos_complete',
    flag: 'kosmos_written',
  },
};

// ===== JOURNAL ENTRIES =====
export const journalTemplates: Record<string, JournalEntry> = {
  european_foundation: {
    id: 'european_foundation',
    title: 'European Foundations',
    content: 'The intellectual foundations laid in Berlin — Kantian philosophy, Enlightenment ideals, the salons of the Herz family. All of this shapes the lens through which I will see the New World.',
    location: 'berlin',
    connections: ['kant_methodology', 'romantic_vision', 'brother_bond'],
    discovered: false,
  },
  kant_methodology: {
    id: 'kant_methodology',
    title: 'Kant\'s Methodology',
    content: 'Systematic observation as the path to truth. Every measurement must be precise, every conclusion must follow from evidence. This is the backbone of my scientific practice.',
    location: 'berlin',
    connections: ['european_foundation', 'instrument_selection'],
    discovered: false,
  },
  romantic_vision: {
    id: 'romantic_vision',
    title: 'The Romantic Vision',
    content: 'Nature is not merely a mechanism to be dissected — it is a living poem to be experienced with all the senses. Science and art are not opposites but partners.',
    location: 'berlin',
    connections: ['european_foundation', 'goethe_synthesis'],
    discovered: false,
  },
  deforestation_climate: {
    id: 'deforestation_climate',
    title: 'Forests & Climate',
    content: 'The destruction of forests alters the climate itself. Trees and water exist in a cycle — remove one, and the other follows. This is perhaps the most important discovery of the expedition.',
    location: 'lake_valencia',
    connections: ['llanos_ecosystem', 'orinoco_biodiversity', 'altitudinal_zonation'],
    discovered: false,
  },
  altitudinal_zonation: {
    id: 'altitudinal_zonation',
    title: 'Altitudinal Zonation',
    content: 'Mountains are worlds stacked upon worlds. Each band of altitude hosts its own ecosystem, its own climate, its own community of life. From tropical to arctic in a single ascent.',
    location: 'andes_foothills',
    connections: ['chimborazo_summit', 'deforestation_climate', 'cosmos_synthesis'],
    discovered: false,
  },
  cosmos_synthesis: {
    id: 'cosmos_synthesis',
    title: 'Cosmos: The Unity of Nature',
    content: 'All of nature is connected — from the smallest moss to the most distant star. The same forces that shape mountains govern the orbits of planets. Everything is one. This is the truth I have spent my life pursuing.',
    location: 'europe_return',
    connections: ['altitudinal_zonation', 'deforestation_climate', 'chimborazo_summit'],
    discovered: false,
  },
  brother_bond: {
    id: 'brother_bond',
    title: 'Brotherhood of Knowledge',
    content: 'Wilhelm and I — we are two halves of the same quest. He seeks the universal grammar of language; I seek the universal grammar of nature. Together, we encompass the full spectrum of human understanding.',
    location: 'berlin',
    connections: ['european_foundation', 'goethe_synthesis'],
    discovered: false,
  },
  instrument_selection: {
    id: 'instrument_selection',
    title: 'The Forty-Two Instruments',
    content: 'Six chronometers, three barometers, telescopes, quadrants, magnetometers, eudiometers, and more. Each one is an eye that sees what human senses cannot. Together, they will translate the language of nature into numbers.',
    location: 'berlin',
    connections: ['kant_methodology', 'tropical_acclimation'],
    discovered: false,
  },
  tropical_acclimation: {
    id: 'tropical_acclimation',
    title: 'Under the Tropical Sun',
    content: 'The heat of the Tropics is unlike anything in Europe. It presses upon you like a living thing. But within this oppressive warmth lies an explosion of life — forms and colors that no European garden could contain.',
    location: 'caracas',
    connections: ['tropical_flora', 'venezuela_arrival'],
    discovered: false,
  },
  venezuela_arrival: {
    id: 'venezuela_arrival',
    title: 'Landfall in Venezuela',
    content: 'After sixty days at sea, the coast of Venezuela rises from the horizon. The air is thick with the scent of flowers unknown to science. Every breath is a discovery.',
    location: 'caracas',
    connections: ['tropical_acclimation', 'european_foundation'],
    discovered: false,
  },
  llanos_ecosystem: {
    id: 'llanos_ecosystem',
    title: 'The Llanos Ecosystem',
    content: 'The great plains are not empty — they teem with life adapted to extremes. Seasonal flooding creates a rhythm of abundance and scarcity that shapes every creature here. The llaneros understand this rhythm in their bones.',
    location: 'llanos',
    connections: ['deforestation_climate', 'jaguar_encounter'],
    discovered: false,
  },
  llanero_knowledge: {
    id: 'llanero_knowledge',
    title: 'Knowledge of the Plains',
    content: 'The llaneros taught me to read the land — where water hides beneath the surface, when the fish run, how the jaguar marks its territory. Their knowledge is as precise as any instrument reading.',
    location: 'llanos',
    connections: ['llanos_ecosystem', 'indigenous_ecology'],
    discovered: false,
  },
  jaguar_encounter: {
    id: 'jaguar_encounter',
    title: 'Eyes in the Darkness',
    content: 'The jaguar is the spirit of the llanos made flesh. To encounter one is to stand at the boundary between civilization and the wild. I felt its gaze and understood something about the nature of predation — and respect.',
    location: 'llanos',
    connections: ['llanos_ecosystem', 'orinoco_biodiversity'],
    discovered: false,
  },
  lake_valencia_data: {
    id: 'lake_valencia_data',
    title: 'Data from the Shrinking Lake',
    content: 'The measurements are irrefutable. Water levels dropping, humidity decreasing, rainfall diminishing — all correlated with the clearance of forests upstream. The trees breathe water into the sky. Remove them, and the sky forgets to rain.',
    location: 'lake_valencia',
    connections: ['deforestation_climate', 'llanos_ecosystem'],
    discovered: false,
  },
  orinoco_biodiversity: {
    id: 'orinoco_biodiversity',
    title: 'Riches of the Orinoco',
    content: 'The Orinoco basin contains more species per square mile than all of Europe combined. Every netful of water, every sweep of the butterfly net reveals forms unknown to science. Life here is profligate, extravagant, overwhelming.',
    location: 'orinoco',
    connections: ['llanos_ecosystem', 'indigenous_ecology'],
    discovered: false,
  },
  indigenous_ecology: {
    id: 'indigenous_ecology',
    title: 'Indigenous Ecological Knowledge',
    content: 'The peoples of the Orinoco have lived in balance with this land for millennia. Their names for species encode ecological relationships. Their agricultural practices sustain rather than deplete. We have much to learn from them.',
    location: 'orinoco',
    connections: ['orinoco_biodiversity', 'llanero_knowledge'],
    discovered: false,
  },
  electric_eels: {
    id: 'electric_eels',
    title: 'The Thunder-Fish',
    content: 'The electric eel discharges up to 650 volts — enough to kill a horse. Their bodies are living batteries, a marvel of biological engineering. This discovery will advance our understanding of electricity itself.',
    location: 'orinoco',
    connections: ['orinoco_biodiversity', 'indigenous_ecology'],
    discovered: false,
  },
  orinoco_mapping: {
    id: 'orinoco_mapping',
    title: 'Mapping the Great River',
    content: 'The Casiquiare channel connects the Orinoco to the Amazon — a natural waterway linking two great river systems. This discovery reshapes our understanding of South American geography.',
    location: 'orinoco',
    connections: ['orinoco_biodiversity', 'altitudinal_zonation'],
    discovered: false,
  },
  vegetation_zones: {
    id: 'vegetation_zones',
    title: 'The Mountain\'s Garden',
    content: 'Each altitude band is a different garden — tropical palms at the base, then oaks, then conifers, then mosses, then lichens, then nothing but ice. Nature paints in vertical strokes.',
    location: 'andes_foothills',
    connections: ['altitudinal_zonation', 'chimborazo_summit'],
    discovered: false,
  },
  barometric_formula: {
    id: 'barometric_formula',
    title: 'The Barometric Formula',
    content: 'At extreme altitude, the barometer reveals the mathematical relationship between height and atmospheric pressure. This formula will allow sailors to calculate ocean depths from surface measurements.',
    location: 'andes_foothills',
    connections: ['altitudinal_zonation', 'chimborazo_summit'],
    discovered: false,
  },
  chimborazo_summit: {
    id: 'chimborazo_summit',
    title: 'Above the World',
    content: 'At 19,286 feet, the world falls away. The curvature of the Earth becomes visible. Up here, you understand that the atmosphere is thin as a breath — the only thing separating life from the void of space.',
    location: 'chimborazo',
    connections: ['altitudinal_zonation', 'naturgemalde_complete', 'cosmos_synthesis'],
    discovered: false,
  },
  naturgemalde_complete: {
    id: 'naturgemalde_complete',
    title: 'The Naturgemälde',
    content: 'The painting of nature is complete — a cross-section of Chimborazo showing all vegetation zones, geological strata, and atmospheric data in a single unified image. It is both scientific diagram and work of art.',
    location: 'chimborazo',
    connections: ['chimborazo_summit', 'cosmos_synthesis'],
    discovered: false,
  },
  new_spain_economy: {
    id: 'new_spain_economy',
    title: 'The Economy of New Spain',
    content: 'New Spain is a land of contradictions — immense wealth extracted from the earth, built upon the suffering of indigenous laborers. The silver flows to Spain while the miners die in darkness.',
    location: 'mexico',
    connections: ['mining_exploitation', 'liberty_contradiction'],
    discovered: false,
  },
  mining_exploitation: {
    id: 'mining_exploitation',
    title: 'The Human Cost of Silver',
    content: 'In the Valenciana mine, I documented both the geological richness and the human tragedy. Hundreds of miners die each year — cave-ins, mercury poisoning, collapsed lungs. The wealth of empires is measured in blood.',
    location: 'mexico',
    connections: ['new_spain_economy', 'liberty_contradiction'],
    discovered: false,
  },
  liberty_contradiction: {
    id: 'liberty_contradiction',
    title: 'The Contradiction of Liberty',
    content: 'Nations that proclaim liberty while practicing slavery — this is the great contradiction of our age. I have seen it in the Spanish colonies and in the American republic. Enlightenment ideals must extend to all, or they are nothing.',
    location: 'mexico',
    connections: ['mining_exploitation', 'cosmos_synthesis'],
    discovered: false,
  },
  geographic_diplomacy: {
    id: 'geographic_diplomacy',
    title: 'Maps as Diplomacy',
    content: 'My charts of New Spain proved invaluable to President Jefferson. Knowledge of geography is power — it shapes borders, enables expansion, determines the fate of nations. Science is never truly neutral.',
    location: 'mexico',
    connections: ['liberty_contradiction', 'new_spain_economy'],
    discovered: false,
  },
  voyage_published: {
    id: 'voyage_published',
    title: 'The Voyage Published',
    content: 'Thirty volumes — the most ambitious scientific publication ever attempted. Every illustration, every table, every observation from five years of extraordinary travel. The world now has a new picture of the Tropics.',
    location: 'europe_return',
    connections: ['cosmos_synthesis', 'goethe_synthesis'],
    discovered: false,
  },
  goethe_synthesis: {
    id: 'goethe_synthesis',
    title: 'The Goethe Synthesis',
    content: 'Goethe taught me that science and poetry are not opposites but partners. The eye that measures is the same eye that marvels. Together, we forged a vision of nature that speaks to both head and heart.',
    location: 'europe_return',
    connections: ['cosmos_synthesis', 'brother_bond', 'romantic_vision'],
    discovered: false,
  },
  darwin_legacy: {
    id: 'darwin_legacy',
    title: 'Passing the Torch',
    content: 'Young Darwin carries the fire forward. He will sail to the ends of the earth, observe with patience, and perhaps discover what I have only glimpsed — the mechanism by which species transform across time.',
    location: 'europe_return',
    connections: ['cosmos_synthesis', 'goethe_synthesis'],
    discovered: false,
  },
};

// ===== NATURGEMLÄLDE NODES =====
export const naturgemaldeTemplates: Record<string, NaturgemaldeNode> = {
  tropical_flora: {
    id: 'tropical_flora',
    label: 'Tropical Flora',
    category: 'flora',
    x: 50,
    y: 85,
    connections: ['subtropical_flora', 'insects'],
  },
  subtropical_flora: {
    id: 'subtropical_flora',
    label: 'Subtropical Forest',
    category: 'flora',
    x: 35,
    y: 70,
    connections: ['temperate_flora', 'tropical_flora'],
  },
  temperate_flora: {
    id: 'temperate_flora',
    label: 'Temperate Oaks',
    category: 'flora',
    x: 45,
    y: 55,
    connections: ['alpine_moss', 'subtropical_flora'],
  },
  alpine_moss: {
    id: 'alpine_moss',
    label: 'Alpine Vegetation',
    category: 'flora',
    x: 55,
    y: 40,
    connections: ['snow_line', 'temperate_flora'],
  },
  snow_line: {
    id: 'snow_line',
    label: 'Permanent Snow',
    category: 'climate',
    x: 50,
    y: 20,
    connections: ['alpine_moss', 'atmosphere'],
  },
  atmosphere: {
    id: 'atmosphere',
    label: 'Atmospheric Pressure',
    category: 'climate',
    x: 75,
    y: 25,
    connections: ['snow_line', 'temperature'],
  },
  temperature: {
    id: 'temperature',
    label: 'Temperature Gradient',
    category: 'climate',
    x: 80,
    y: 50,
    connections: ['atmosphere', 'geology'],
  },
  geology: {
    id: 'geology',
    label: 'Volcanic Geology',
    category: 'geology',
    x: 25,
    y: 45,
    connections: ['temperature', 'minerals'],
  },
  minerals: {
    id: 'minerals',
    label: 'Mineral Deposits',
    category: 'geology',
    x: 20,
    y: 70,
    connections: ['geology', 'insects'],
  },
  insects: {
    id: 'insects',
    label: 'Insect Life',
    category: 'fauna',
    x: 65,
    y: 80,
    connections: ['tropical_flora', 'condors'],
  },
  condors: {
    id: 'condors',
    label: 'Andean Condors',
    category: 'fauna',
    x: 70,
    y: 35,
    connections: ['snow_line', 'insects'],
  },
};
