import { GameAction, Location, Storyline, Relationship, RandomEvent, NaturgemaldeNode } from './types';

// ===== LOCATIONS =====
export const initialLocations: Record<string, Location> = {
  berlin: {
    id: 'berlin', name: 'Berlin, Prussia', region: 'Europe',
    description: 'The grand capital. Salons buzz with Enlightenment discourse. Your mother has passed, leaving you free to pursue your dream.',
    atmosphere: 'Candlelit libraries. The weight of possibility.',
    actions: ['berlin_prepare', 'berlin_saloon', 'berlin_study', 'berlin_rest', 'berlin_instruments'],
    connections: ['caracas'],
    discovered: true,
  },
  caracas: {
    id: 'caracas', name: 'Caracas, Venezuela', region: 'South America',
    description: 'The warm Caribbean air greets you. The Captaincy General of Venezuela stretches before you — a land of dramatic contrasts.',
    atmosphere: 'Tropical heat. Colonial architecture. Unfamiliar flowers.',
    actions: ['caracas_explore', 'caracas_bonpland', 'caracas_market', 'caracas_rest', 'caracas_collect'],
    connections: ['berlin', 'llanos', 'lake_valencia'],
    discovered: false,
  },
  llanos: {
    id: 'llanos', name: 'The Venezuelan Llanos', region: 'South America',
    description: 'Vast, treeless plains extend to the horizon. Home to wild horses, capybaras, and the llaneros.',
    atmosphere: 'Endless grass. Blazing sun. Thunder of hooves.',
    actions: ['llanos_explore', 'llanos_survive', 'llanos_llanero', 'llanos_hunt', 'llanos_observe'],
    connections: ['caracas', 'orinoco'],
    discovered: false,
  },
  lake_valencia: {
    id: 'lake_valencia', name: 'Lake Valencia', region: 'South America',
    description: 'Once a great body of water, the lake has been receding alarmingly. Forests cleared upstream.',
    atmosphere: 'Shallow waters. Exposed mudflats. Stumps of felled trees.',
    actions: ['valencia_measure', 'valencia_investigate', 'valencia_farmer', 'valencia_sketch', 'valencia_rest'],
    connections: ['caracas', 'llanos'],
    discovered: false,
  },
  orinoco: {
    id: 'orinoco', name: 'The Orinoco River', region: 'South America',
    description: 'The great river winds through dense jungle. Its waters teem with life — and danger.',
    atmosphere: 'Dark waters. Jungle cacophony. Humidity that clings.',
    actions: ['orinoco_navigate', 'orinoco_eels', 'orinoco_indigenous', 'orinoco_collect', 'orinoco_rest'],
    connections: ['llanos', 'andes_foothills'],
    discovered: false,
  },
  andes_foothills: {
    id: 'andes_foothills', name: 'Andes Foothills', region: 'South America',
    description: 'The great mountain chain rises before you. Vegetation changes dramatically with altitude.',
    atmosphere: 'Cool mountain air. Changing ecosystems. Call of condors.',
    actions: ['andes_climb', 'andes_measure', 'andes_observe', 'andes_guide', 'andes_rest'],
    connections: ['orinoco', 'chimborazo'],
    discovered: false,
  },
  chimborazo: {
    id: 'chimborazo', name: 'Chimborazo, Ecuador', region: 'South America',
    description: 'The great volcano towers above all. At 19,286 feet, believed to be the highest peak in the world.',
    atmosphere: 'Crystalline air. Vertiginous heights. The curve of the Earth.',
    actions: ['chimborazo_ascent', 'chimborazo_measure', 'chimborazo_naturgemalde', 'chimborazo_survive', 'chimborazo_rest'],
    connections: ['andes_foothills', 'mexico'],
    requiredFlag: 'reached_andes',
    discovered: false,
  },
  mexico: {
    id: 'mexico', name: 'New Spain (Mexico)', region: 'North America',
    description: 'A land of immense wealth and deep inequality. Silver mines pour riches into Spanish coffers.',
    atmosphere: 'Colonial grandeur. Silver and stone. Tension between worlds.',
    actions: ['mexico_survey', 'mexico_mine', 'mexico_jefferson', 'mexico_political', 'mexico_rest'],
    connections: ['chimborazo', 'paris'],
    discovered: false,
  },
  paris: {
    id: 'paris', name: 'Paris, France', region: 'Europe',
    description: 'You return to Europe after nearly five years. Now begins the great work of synthesis.',
    atmosphere: 'Scholarly intensity. The weight of accumulated knowledge.',
    actions: ['paris_write', 'paris_goethe', 'paris_lecture', 'paris_darwin', 'paris_kosmos'],
    connections: ['mexico'],
    requiredFlag: 'returned_europe',
    discovered: false,
  },
};

// ===== ACTIONS (Citizen Sleeper style - assigned dice) =====
export const allActions: Record<string, GameAction> = {
  // === BERLIN ===
  berlin_prepare: {
    id: 'berlin_prepare', name: 'Prepare for Expedition', location: 'berlin',
    description: 'Study maps, plan routes, and ready yourself for the journey ahead.',
    dieRequired: 1, skill: 'logic',
    effects: { resources: { data: 3 }, flag: 'expedition_ready', storyline: 'expedition_prep' },
    successText: 'Your preparations are meticulous. Every contingency considered, every route mapped. The New World awaits.',
    failText: 'The scope of preparation is overwhelming. You feel underready, but time presses.',
    available: true,
  },
  berlin_saloon: {
    id: 'berlin_saloon', name: 'Attend the Salon', location: 'berlin',
    description: 'Visit Henriette Herz\'s salon. Intellectual discourse and potential alliances.',
    dieRequired: 2, skill: 'empathy',
    effects: { resources: { credits: 5 }, relationship: { id: 'herz', change: 1 }, storyline: 'intellectual_network' },
    successText: 'Henriette welcomes you warmly. The conversation flows — Kant, nature, the possibilities of the New World. You leave with new contacts and renewed purpose.',
    failText: 'The salon is lively but you feel out of place. Still, you exchange pleasantries.',
    available: true,
  },
  berlin_study: {
    id: 'berlin_study', name: 'Study Natural Philosophy', location: 'berlin',
    description: 'Spend time in the library, reading the latest scientific works.',
    dieRequired: 3, skill: 'logic',
    effects: { resources: { data: 5 }, storyline: 'scientific_foundation' },
    successText: 'A breakthrough in your reading! You connect Blumenbach\'s theories on vegetation with your own observations. The foundations of your worldview crystallize.',
    failText: 'The texts are dense and your mind wanders. Some knowledge absorbed, but no breakthrough.',
    available: true,
  },
  berlin_rest: {
    id: 'berlin_rest', name: 'Rest & Reflect', location: 'berlin',
    description: 'Take time to recover your strength and center yourself.',
    dieRequired: 1,
    effects: { resources: { vitality: 8 } },
    successText: 'You sleep deeply and wake refreshed. The weight of your mother\'s passing lifts, if only slightly.',
    failText: 'Restless sleep. Dreams of mountains and jungles.',
    available: true,
  },
  berlin_instruments: {
    id: 'berlin_instruments', name: 'Calibrate Instruments', location: 'berlin',
    description: 'Test and calibrate your 42 scientific instruments before departure.',
    dieRequired: 4, skill: 'logic',
    cost: { credits: 10 },
    effects: { resources: { instruments: 15, data: 3 }, storyline: 'expedition_prep' },
    successText: 'Every instrument sings true. The barometers, the eudiometers, the magnetometers — all calibrated to perfection. Your tools are extensions of your senses.',
    failText: 'Several instruments need repair. You spend more than expected, but the essentials are sound.',
    available: true,
  },

  // === CARACAS ===
  caracas_explore: {
    id: 'caracas_explore', name: 'Explore the Coast', location: 'caracas',
    description: 'Survey the coastal region, cataloging new species and geological formations.',
    dieRequired: 2, skill: 'aesthetics',
    effects: { resources: { data: 4 }, storyline: 'tropical_discovery' },
    successText: 'The coastal flora is extraordinary! Species you have never seen — orchids of impossible color, trees that seem to breathe moisture from the air itself.',
    failText: 'The heat is oppressive. You collect a few specimens but struggle to focus.',
    available: true,
  },
  caracas_bonpland: {
    id: 'caracas_bonpland', name: 'Work with Bonpland', location: 'caracas',
    description: 'Collaborate with your companion on botanical collection and classification.',
    dieRequired: 2, skill: 'empathy',
    effects: { relationship: { id: 'bonpland', change: 2 }, resources: { data: 3 }, storyline: 'bonpland_friendship' },
    successText: 'Bonpland\'s enthusiasm is infectious. Together you press specimens, debate classifications, and share wonder at the botanical wealth surrounding you.',
    failText: 'A productive session, though you disagree on a classification. Bonpland is stubborn but brilliant.',
    available: true,
  },
  caracas_market: {
    id: 'caracas_market', name: 'Trade at the Market', location: 'caracas',
    description: 'Resupply at the local market. Exchange European goods for local provisions.',
    dieRequired: 1,
    cost: { credits: 5 },
    effects: { resources: { supplies: 15 } },
    successText: 'Good trade. You acquire dried fish, tropical fruits, and a guide who knows the interior paths.',
    failText: 'Prices are high. You get what you can, but your credits dwindle.',
    available: true,
  },
  caracas_rest: {
    id: 'caracas_rest', name: 'Rest in Caracas', location: 'caracas',
    description: 'Recover from the sea voyage in a shaded room with cool water.',
    dieRequired: 1,
    effects: { resources: { vitality: 10 } },
    successText: 'The tropical breeze through an open window. You sleep deeply and wake with renewed strength.',
    failText: 'The heat persists even in sleep. You wake stiff but functional.',
    available: true,
  },
  caracas_collect: {
    id: 'caracas_collect', name: 'Collect Specimens', location: 'caracas',
    description: 'Gather plant and mineral samples for your collection.',
    dieRequired: 3, skill: 'logic',
    cost: { instruments: 2 },
    effects: { resources: { data: 6 }, storyline: 'tropical_discovery' },
    successText: 'A remarkable day of collection! Three species new to European science, plus geological samples that hint at the region\'s volcanic origins.',
    failText: 'The specimens are damaged in the humidity. Some data lost, but the effort itself teaches you about preservation.',
    available: true,
  },

  // === LLANOS ===
  llanos_explore: {
    id: 'llanos_explore', name: 'Traverse the Plains', location: 'llanos',
    description: 'Ride across the vast llanos, observing the ecosystem.',
    dieRequired: 2, skill: 'aesthetics',
    cost: { supplies: 3 },
    effects: { resources: { data: 4 }, storyline: 'llanos_journey' },
    successText: 'The plains unfold like a living painting. You observe the rhythm of the grasslands — seasonal flooding, the migration of herds, the delicate balance of this seemingly empty landscape.',
    failText: 'The sun beats down mercilessly. You see little beyond the shimmer of heat haze.',
    available: true,
  },
  llanos_survive: {
    id: 'llanos_survive', name: 'Find Water & Shelter', location: 'llanos',
    description: 'Locate water sources and safe camping spots on the plains.',
    dieRequired: 2, skill: 'logic',
    effects: { resources: { supplies: 8, vitality: 3 } },
    successText: 'Your knowledge of hydrology pays off. You find a spring where the grass grows slightly greener — underground water close to the surface.',
    failText: 'A long, thirsty day. You find water eventually, but the search costs energy.',
    available: true,
  },
  llanos_llanero: {
    id: 'llanos_llanero', name: 'Speak with the Llaneros', location: 'llanos',
    description: 'Engage with the local horsemen. Learn their knowledge of the land.',
    dieRequired: 3, skill: 'empathy',
    effects: { relationship: { id: 'indigenous', change: 2 }, resources: { data: 3, supplies: 5 }, storyline: 'indigenous_knowledge' },
    successText: 'The llanero shares his knowledge freely once he senses your respect. He shows you where the water hides, when the fish run, how to read the weather in the clouds.',
    failText: 'The llanero is suspicious of foreigners. You exchange only pleasantries.',
    available: true,
  },
  llanos_hunt: {
    id: 'llanos_hunt', name: 'Hunt for Food', location: 'llanos',
    description: 'Hunt capybara or birds to supplement your supplies.',
    dieRequired: 3, skill: 'logic',
    cost: { instruments: 1 },
    effects: { resources: { supplies: 12 } },
    successText: 'A successful hunt. Enough meat to feed the expedition for several days. You also observe the animal\'s behavior — its relationship to the grassland ecosystem.',
    failText: 'The prey is elusive. You return empty-handed but with renewed respect for the difficulty of survival here.',
    available: true,
  },
  llanos_observe: {
    id: 'llanos_observe', name: 'Observe Wildlife', location: 'llanos',
    description: 'Patiently observe the animals of the plains, documenting behavior.',
    dieRequired: 4, skill: 'aesthetics',
    effects: { resources: { data: 7 }, storyline: 'llanos_journey' },
    successText: 'Hours of patient observation reveal the intricate social structure of the capybara herds, the hunting patterns of the jaguars at dusk. This is ecology before the word existed.',
    failText: 'The animals are wary. You catch only glimpses, but each one is precious.',
    available: true,
  },

  // === LAKE VALENCIA ===
  valencia_measure: {
    id: 'valencia_measure', name: 'Measure the Lake', location: 'lake_valencia',
    description: 'Take systematic measurements of water levels, temperature, and surrounding conditions.',
    dieRequired: 3, skill: 'logic',
    cost: { instruments: 3 },
    effects: { resources: { data: 8 }, storyline: 'climate_discovery' },
    successText: 'The data is conclusive. Water levels dropping, humidity decreasing — all correlated with the clearance of forests upstream. You are witnessing human-induced climate change.',
    failText: 'Your measurements are inconsistent. The variables are too many. You need more data.',
    available: true,
  },
  valencia_investigate: {
    id: 'valencia_investigate', name: 'Investigate Deforestation', location: 'lake_valencia',
    description: 'Study the cleared forests upstream and their relationship to the lake.',
    dieRequired: 2, skill: 'logic',
    effects: { resources: { data: 5 }, storyline: 'climate_discovery' },
    successText: 'The connection is clear: trees transpire water into the atmosphere. Remove the trees, remove the rain. The forest and the lake are one system.',
    failText: 'The evidence is suggestive but not conclusive. You mark this as a hypothesis to be tested.',
    available: true,
  },
  valencia_farmer: {
    id: 'valencia_farmer', name: 'Talk to Local Farmers', location: 'lake_valencia',
    description: 'Speak with farmers about the changing landscape.',
    dieRequired: 2, skill: 'empathy',
    effects: { relationship: { id: 'indigenous', change: 1 }, resources: { data: 3 } },
    successText: 'The farmer\'s grandfather remembered when boats sailed where cattle now graze. His testimony confirms your measurements — the change is real, and accelerating.',
    failText: 'The farmer is suspicious of your questions. "The land provides," he says dismissively.',
    available: true,
  },
  valencia_sketch: {
    id: 'valencia_sketch', name: 'Sketch the Landscape', location: 'lake_valencia',
    description: 'Create detailed illustrations of the shrinking lake and its surroundings.',
    dieRequired: 3, skill: 'aesthetics',
    effects: { resources: { data: 4 }, storyline: 'climate_discovery' },
    successText: 'Your sketch captures what numbers cannot — the grief of a wounded landscape. The exposed mudflats, the stumps, the receding water line. Art and science united.',
    failText: 'The landscape is depressing and your hand heavy. The sketch is functional but lacks the power you seek.',
    available: true,
  },
  valencia_rest: {
    id: 'valencia_rest', name: 'Rest by the Lake', location: 'lake_valencia',
    description: 'Camp by the remaining water and recover your strength.',
    dieRequired: 1,
    effects: { resources: { vitality: 8, supplies: -2 } },
    successText: 'The remaining waters lap gently at the shore. You rest, thinking about the connections between all things.',
    failText: 'The mosquitoes are relentless. Sleep is fitful at best.',
    available: true,
  },

  // === ORINOCO ===
  orinoco_navigate: {
    id: 'orinoco_navigate', name: 'Navigate the River', location: 'orinoco',
    description: 'Chart the river\'s course using astronomical instruments.',
    dieRequired: 3, skill: 'logic',
    cost: { instruments: 2 },
    effects: { resources: { data: 6 }, storyline: 'river_mapping' },
    successText: 'Your celestial navigation is flawless. You map a channel connecting the Orinoco to the Amazon — a discovery that reshapes the map of South America.',
    failText: 'Cloud cover prevents observations. You drift, waiting for clear skies.',
    available: true,
  },
  orinoco_eels: {
    id: 'orinoco_eels', name: 'Study Electric Eels', location: 'orinoco',
    description: 'Attempt to capture and study the legendary electric eels.',
    dieRequired: 5, skill: 'logic',
    cost: { instruments: 3, supplies: 5 },
    effects: { resources: { data: 12 }, storyline: 'electric_discovery' },
    successText: 'The indigenous people drive horses into the pool. The eels discharge against the horses\' legs, exhausting their electrical reserves. You collect specimens safely — measuring the most powerful bioelectricity known to science.',
    failText: 'The process is chaotic. You receive a painful shock that leaves your hand numb. Some specimens are lost in the struggle.',
    available: true,
  },
  orinoco_indigenous: {
    id: 'orinoco_indigenous', name: 'Learn from Indigenous Guides', location: 'orinoco',
    description: 'Exchange knowledge with the peoples who have lived here for millennia.',
    dieRequired: 3, skill: 'empathy',
    effects: { relationship: { id: 'indigenous', change: 3 }, resources: { data: 5, supplies: 5 }, storyline: 'indigenous_knowledge' },
    successText: 'Your respect opens doors. The guides share their names for species — each encoding ecological relationships. Their agricultural practices sustain rather than deplete. You realize European science has much to learn.',
    failText: 'The language barrier is significant. You communicate through gestures and shared observation.',
    available: true,
  },
  orinoco_collect: {
    id: 'orinoco_collect', name: 'Collect River Specimens', location: 'orinoco',
    description: 'Gather aquatic specimens from the river\'s rich waters.',
    dieRequired: 2, skill: 'logic',
    cost: { instruments: 2 },
    effects: { resources: { data: 5 }, storyline: 'tropical_discovery' },
    successText: 'The river teems with life. Fish of impossible colors, plants that float and dive, insects that skate on the surface. Each specimen a new entry in the catalog of nature.',
    failText: 'The water is murky and the specimens few. But even failure teaches — you learn about the river\'s seasonal rhythms.',
    available: true,
  },
  orinoco_rest: {
    id: 'orinoco_rest', name: 'Rest on the Riverbank', location: 'orinoco',
    description: 'Make camp on the bank and recover from the journey.',
    dieRequired: 1,
    effects: { resources: { vitality: 6 } },
    successText: 'The river\'s song carries you to sleep. You dream in Portuguese and Spanish, in the language of water.',
    failText: 'The humidity is suffocating. Insects swarm. You rest, but do not recover.',
    available: true,
  },

  // === ANDES ===
  andes_climb: {
    id: 'andes_climb', name: 'Climb Higher', location: 'andes_foothills',
    description: 'Ascend further into the mountains, observing vegetation zones.',
    dieRequired: 3, skill: 'logic',
    cost: { supplies: 4, vitality: -3 },
    effects: { resources: { data: 7 }, storyline: 'altitudinal_zonation' },
    successText: 'Each hundred meters brings a new world. Tropical palms give way to oaks, then conifers, then mosses. You are climbing through the climate zones of an entire continent compressed into a single mountain.',
    failText: 'The altitude takes its toll. You turn back, gasping, but the data you gathered is valuable.',
    available: true,
  },
  andes_measure: {
    id: 'andes_measure', name: 'Take Barometric Readings', location: 'andes_foothills',
    description: 'Measure atmospheric pressure at various altitudes.',
    dieRequired: 4, skill: 'logic',
    cost: { instruments: 3 },
    effects: { resources: { data: 8 }, storyline: 'altitudinal_zonation' },
    successText: 'The barometric formula emerges from your data — the precise mathematical relationship between altitude and pressure. This will allow calculations of ocean depth from surface measurements.',
    failText: 'The cold makes your fingers clumsy. Some readings are unreliable, but the pattern is visible.',
    available: true,
  },
  andes_observe: {
    id: 'andes_observe', name: 'Document Vegetation Zones', location: 'andes_foothills',
    description: 'Catalog the changing plant life as you ascend.',
    dieRequired: 3, skill: 'aesthetics',
    effects: { resources: { data: 6 }, storyline: 'altitudinal_zonation' },
    successText: 'Each zone is a different garden, a different world. Your sketches capture not just species but the character of each altitude — the mood, the quality of light, the sound of wind through different leaves.',
    failText: 'The transitions blur. You struggle to capture the subtle boundaries between zones.',
    available: true,
  },
  andes_guide: {
    id: 'andes_guide', name: 'Consult Mountain Guide', location: 'andes_foothills',
    description: 'Speak with local guides about the path to Chimborazo.',
    dieRequired: 3, skill: 'empathy',
    effects: { relationship: { id: 'indigenous', change: 2 }, flag: 'reached_andes', storyline: 'chimborazo_prep' },
    successText: 'The guide studies your face and sees determination. "You are different from the others," he says. "I will take you as high as the mountain allows." The path to Chimborazo opens.',
    failText: 'The guide is cautious. "The mountain kills the unprepared," he warns. But he gives you directions.',
    available: true,
  },
  andes_rest: {
    id: 'andes_rest', name: 'Rest at Camp', location: 'andes_foothills',
    description: 'Recover at base camp before attempting higher altitudes.',
    dieRequired: 1,
    effects: { resources: { vitality: 10 } },
    successText: 'The mountain air, though thin, is invigorating. You sleep deeply and wake with clear eyes.',
    failText: 'The cold seeps into your bones. Sleep is fitful, punctuated by dreams of falling.',
    available: true,
  },

  // === CHIMBORAZO ===
  chimborazo_ascent: {
    id: 'chimborazo_ascent', name: 'Attempt the Summit', location: 'chimborazo',
    description: 'The final push to the top of the world. Everything leads to this.',
    dieRequired: 5, skill: 'logic',
    cost: { supplies: 8, instruments: 5, vitality: -10 },
    effects: { resources: { data: 15 }, flag: 'summit_reached', storyline: 'chimborazo_ascent' },
    successText: '19,286 feet. You stand higher than any human in history. The world curves below you. The air is so thin each breath is a victory. You have touched the sky.',
    failText: 'Altitude sickness overwhelms you. 500 feet from the summit, you must turn back. The mountain will keep its secret — for now.',
    available: true,
  },
  chimborazo_measure: {
    id: 'chimborazo_measure', name: 'Measure at Altitude', location: 'chimborazo',
    description: 'Take scientific readings at extreme altitude.',
    dieRequired: 4, skill: 'logic',
    cost: { instruments: 4 },
    effects: { resources: { data: 10 }, storyline: 'chimborazo_ascent' },
    successText: 'Every reading is precious. The thermometer, the barometer, the eudiometer — each instrument tells part of the story of this altitude. The data will rewrite the textbooks.',
    failText: 'The cold seizes your instruments. Mercury contracts unpredictably. Some data is lost to the mountain.',
    available: true,
  },
  chimborazo_naturgemalde: {
    id: 'chimborazo_naturgemalde', name: 'Create the Naturgemälde', location: 'chimborazo',
    description: 'Synthesize all your observations into the great painting of nature.',
    dieRequired: 5, skill: 'aesthetics',
    cost: { instruments: 2 },
    effects: { resources: { data: 20 }, flag: 'naturgemalde_complete', storyline: 'naturgemalde_creation' },
    successText: 'The painting takes shape — a cross-section of the mountain showing every zone of life, from tropical base to eternal ice. It is both scientific diagram and work of art. It is the most beautiful thing you have ever created.',
    failText: 'The synthesis eludes you. Too much data, too many observations. The fragments refuse to cohere into a unified vision.',
    available: true,
    requiredFlag: 'summit_reached',
  },
  chimborazo_survive: {
    id: 'chimborazo_survive', name: 'Endure the Cold', location: 'chimborazo',
    description: 'Fight against hypothermia and altitude sickness.',
    dieRequired: 3, skill: 'logic',
    effects: { resources: { vitality: 8 } },
    successText: 'You know the signs of altitude sickness. You breathe steadily, keep moving, drink melted snow. Your body adapts, if slowly.',
    failText: 'The cold is an enemy you cannot fight with instruments alone. You lose feeling in your fingers.',
    available: true,
  },
  chimborazo_rest: {
    id: 'chimborazo_rest', name: 'Rest at High Camp', location: 'chimborazo',
    description: 'Recover at the high camp between summit attempts.',
    dieRequired: 1,
    cost: { supplies: 3 },
    effects: { resources: { vitality: 12 } },
    successText: 'Wrapped in furs, sipping coca tea, you rest. The stars above are impossibly bright. You understand why the ancients worshipped mountains.',
    failText: 'Sleep comes in fragments. The altitude makes every breath a conscious effort.',
    available: true,
  },

  // === MEXICO ===
  mexico_survey: {
    id: 'mexico_survey', name: 'Survey the Territory', location: 'mexico',
    description: 'Chart the roads and geography of New Spain with precision.',
    dieRequired: 3, skill: 'logic',
    cost: { instruments: 3 },
    effects: { resources: { data: 8 }, storyline: 'colonial_survey' },
    successText: 'Your elevation profiles are masterworks of precision. Every hill, every river, every road mapped with unprecedented accuracy. This data will reshape European understanding of the Americas.',
    failText: 'The terrain is complex and your instruments struggle with the extreme variations. The survey is incomplete.',
    available: true,
  },
  mexico_mine: {
    id: 'mexico_mine', name: 'Analyze the Silver Mine', location: 'mexico',
    description: 'Study the Valenciana mine — its geology, economics, and human cost.',
    dieRequired: 4, skill: 'political',
    cost: { vitality: -5 },
    effects: { resources: { data: 10, credits: 10 }, storyline: 'colonial_critique' },
    successText: 'Three days in the mine reveal everything — the geological richness, the economic system, the human cost. Your analysis is balanced, damning, and irrefutable.',
    failText: 'The darkness and suffering overwhelm your objectivity. You record data but struggle to maintain the detachment of science.',
    available: true,
  },
  mexico_jefferson: {
    id: 'mexico_jefferson', name: 'Meet President Jefferson', location: 'mexico',
    description: 'Share your geographic knowledge with the American president.',
    dieRequired: 4, skill: 'political',
    effects: { resources: { credits: 15, data: 5 }, relationship: { id: 'scientific_community', change: 2 }, storyline: 'colonial_survey' },
    successText: 'Jefferson is fascinated by your data. You share maps, measurements, and observations. In return, he shares his vision for the new nation. A meeting of minds across the Atlantic.',
    failText: 'The meeting is cordial but superficial. Jefferson is interested in data, not philosophy. You exchange pleasantries and maps.',
    available: true,
  },
  mexico_political: {
    id: 'mexico_political', name: 'Observe Colonial Society', location: 'mexico',
    description: 'Study the social structures of New Spain — the inequalities, the contradictions.',
    dieRequired: 3, skill: 'political',
    effects: { resources: { data: 6 }, storyline: 'colonial_critique' },
    successText: 'You see clearly now — the Enlightenment ideals of Europe, proclaimed so loudly, ring hollow in the colonies. Liberty for some, bondage for others. You document everything.',
    failText: 'The complexity of colonial society resists easy analysis. You observe but do not yet understand.',
    available: true,
  },
  mexico_rest: {
    id: 'mexico_rest', name: 'Rest in Mexico City', location: 'mexico',
    description: 'Recover in the grand capital of New Spain.',
    dieRequired: 1,
    cost: { credits: 5 },
    effects: { resources: { vitality: 10, supplies: 5 } },
    successText: 'The city\'s grandeur is restorative. Good food, clean water, intellectual conversation. You remember why you began this journey.',
    failText: 'The city is expensive and the food heavy. You rest, but do not fully recover.',
    available: true,
  },

  // === PARIS ===
  paris_write: {
    id: 'paris_write', name: 'Write Your Findings', location: 'paris',
    description: 'Transform your field notes into publishable scientific works.',
    dieRequired: 3, skill: 'logic',
    effects: { resources: { data: 8 }, storyline: 'publication' },
    successText: 'The words flow. Five years of observation distilled into clear, elegant prose. Your narrative of travel will become one of the most influential scientific works of the century.',
    failText: 'The material is vast and unwieldy. You write, cross out, rewrite. Progress is slow.',
    available: true,
  },
  paris_goethe: {
    id: 'paris_goethe', name: 'Meet with Goethe', location: 'paris',
    description: 'Correspond and meet with your great friend, the poet-scientist.',
    dieRequired: 3, skill: 'aesthetics',
    effects: { relationship: { id: 'goethe', change: 3 }, resources: { data: 5 }, storyline: 'goethe_synthesis' },
    successText: 'Goethe embraces you. "You have shown me what I always felt — that nature is a poem." Together you discuss the unity of knowledge, the marriage of science and art. These conversations will shape your masterwork.',
    failText: 'The meeting is brief but warm. Goethe is busy with his own projects, but his encouragement sustains you.',
    available: true,
  },
  paris_lecture: {
    id: 'paris_lecture', name: 'Deliver a Lecture', location: 'paris',
    description: 'Share your discoveries with the scientific community.',
    dieRequired: 4, skill: 'empathy',
    effects: { resources: { credits: 10, data: 5 }, relationship: { id: 'scientific_community', change: 2 }, storyline: 'publication' },
    successText: 'The lecture hall is packed. Your words paint pictures of tropical forests, volcanic peaks, electric eels. The audience is transfixed. You have made science popular.',
    failText: 'Nerves get the better of you. The lecture is informative but lacks the poetry that makes your writing sing.',
    available: true,
  },
  paris_darwin: {
    id: 'paris_darwin', name: 'Mentor Young Darwin', location: 'paris',
    description: 'A young naturalist named Charles seeks your counsel before his own voyage.',
    dieRequired: 4, skill: 'empathy',
    effects: { relationship: { id: 'scientific_community', change: 3 }, storyline: 'legacy' },
    successText: 'Darwin\'s eyes burn with the same fire you once had. "Take careful measurements," you tell him, "but remember — seek the connections. The web of life is the great mystery." He will remember.',
    failText: 'The young man is eager but unfocused. You offer what advice you can, hoping it takes root.',
    available: true,
  },
  paris_kosmos: {
    id: 'paris_kosmos', name: 'Write Kosmos', location: 'paris',
    description: 'Your final and greatest work — the unification of all knowledge.',
    dieRequired: 6, skill: 'aesthetics',
    effects: { resources: { data: 25 }, flag: 'kosmos_written', storyline: 'kosmos' },
    successText: 'Kosmos is complete. Five volumes that unite astronomy and geography, physics and poetry, data and beauty. You have shown the world that nature is a living, breathing whole. Your life\'s work is done.',
    failText: 'The synthesis remains incomplete. The threads of knowledge are too many, too complex. But each attempt brings you closer.',
    available: true,
    requiredFlag: 'naturgemalde_complete',
  },
};

// ===== STORYLINES (parallel arcs like Citizen Sleeper) =====
export const initialStorylines: Storyline[] = [
  {
    id: 'expedition_prep', title: 'The Expedition Prepares', icon: '🧭',
    description: 'Prepare for the journey to the New World.',
    currentStage: 0,
    stages: [
      { id: 'prep_1', title: 'Study & Plan', description: 'Research the route and prepare your mind.', requirement: { type: 'action', target: 'berlin_prepare' }, text: 'Your preparations take shape. Maps cover every surface of your study.', completed: false },
      { id: 'prep_2', title: 'Instruments Ready', description: 'Calibrate all 42 instruments.', requirement: { type: 'action', target: 'berlin_instruments' }, text: 'Every instrument sings true. You are ready.', completed: false, reward: { flag: 'expedition_ready' } },
    ],
  },
  {
    id: 'bonpland_friendship', title: 'Bonpland\'s Friendship', icon: '🌱',
    description: 'Build your partnership with Aimé Bonpland.',
    currentStage: 0,
    stages: [
      { id: 'bon_1', title: 'First Collaboration', description: 'Work together on botanical collection.', requirement: { type: 'action', target: 'caracas_bonpland' }, text: 'Bonpland\'s enthusiasm is infectious. A partnership forms.', completed: false },
      { id: 'bon_2', title: 'Deepening Trust', description: 'Share your vision of unified science.', requirement: { type: 'relationship', target: 'bonpland', value: 4 }, text: 'Bonpland understands your vision. "We see the world differently, but we see it together."', completed: false, reward: { relationship: { id: 'bonpland', change: 2 } } },
      { id: 'bon_3', title: 'Partners for Life', description: 'Your bond is unbreakable.', requirement: { type: 'relationship', target: 'bonpland', value: 7 }, text: 'Through hardship and wonder, your friendship has become the foundation of the expedition.', completed: false, reward: { flag: 'bonpland_partner' } },
    ],
  },
  {
    id: 'climate_discovery', title: 'Forests & Climate', icon: '🌳',
    description: 'Discover the connection between deforestation and climate.',
    currentStage: 0,
    stages: [
      { id: 'clim_1', title: 'The Shrinking Lake', description: 'Notice Lake Valencia\'s recession.', requirement: { type: 'action', target: 'valencia_measure' }, text: 'The data is clear. The lake is shrinking. But why?', completed: false },
      { id: 'clim_2', title: 'The Forest Connection', description: 'Link deforestation to reduced rainfall.', requirement: { type: 'data', target: 'data', value: 25 }, text: 'The trees breathe water into the sky. Remove the trees, remove the rain. You have discovered human-induced climate change.', completed: false, reward: { flag: 'climate_discovered' } },
    ],
  },
  {
    id: 'indigenous_knowledge', title: 'Voices of the Land', icon: '🪶',
    description: 'Learn from the peoples who have lived here for millennia.',
    currentStage: 0,
    stages: [
      { id: 'ind_1', title: 'First Contact', description: 'Begin building relationships with indigenous peoples.', requirement: { type: 'relationship', target: 'indigenous', value: 2 }, text: 'Trust is slowly earned. They begin to share their knowledge.', completed: false },
      { id: 'ind_2', title: 'Deep Knowledge', description: 'Gain significant indigenous trust.', requirement: { type: 'relationship', target: 'indigenous', value: 5 }, text: 'Their ecological knowledge is vast — centuries of observation encoded in language and practice.', completed: false, reward: { flag: 'indigenous_ally' } },
      { id: 'ind_3', title: 'Two Ways of Knowing', description: 'Synthesize European and indigenous knowledge.', requirement: { type: 'relationship', target: 'indigenous', value: 8 }, text: 'You understand now: science is not the only path to knowledge. The web of life is known in many languages.', completed: false, reward: { flag: 'knowledge_synthesis' } },
    ],
  },
  {
    id: 'altitudinal_zonation', title: 'The Mountain\'s Layers', icon: '⛰️',
    description: 'Document the vegetation zones of the Andes.',
    currentStage: 0,
    stages: [
      { id: 'alt_1', title: 'First Ascent', description: 'Begin climbing into the mountains.', requirement: { type: 'action', target: 'andes_climb' }, text: 'Each step upward reveals a new world. The vegetation changes like pages in a book.', completed: false },
      { id: 'alt_2', title: 'The Pattern Emerges', description: 'Map the vegetation zones systematically.', requirement: { type: 'data', target: 'data', value: 50 }, text: 'The pattern is clear: altitude creates climate, climate creates ecology. Every mountain is a compressed continent.', completed: false, reward: { flag: 'zonation_mapped' } },
    ],
  },
  {
    id: 'chimborazo_ascent', title: 'The Summit of the World', icon: '🌋',
    description: 'Attempt the record-breaking ascent of Chimborazo.',
    currentStage: 0,
    stages: [
      { id: 'chim_1', title: 'The Attempt', description: 'Push for the summit.', requirement: { type: 'flag', target: 'summit_reached' }, text: '19,286 feet. You stand higher than any human in history. The world curves below you.', completed: false, reward: { flag: 'summit_reached' } },
    ],
  },
  {
    id: 'naturgemalde_creation', title: 'The Painting of Nature', icon: '🖼️',
    description: 'Create your masterwork — the Naturgemälde.',
    currentStage: 0,
    stages: [
      { id: 'nat_1', title: 'The Vision', description: 'Synthesize all observations into a unified image.', requirement: { type: 'flag', target: 'naturgemalde_complete' }, text: 'The Naturgemälde takes shape — a cross-section of Chimborazo showing all life, from base to summit, in one unified vision.', completed: false },
    ],
  },
  {
    id: 'colonial_critique', title: 'The Colonial Critique', icon: '⚖️',
    description: 'Document and critique the colonial system.',
    currentStage: 0,
    stages: [
      { id: 'col_1', title: 'Observation', description: 'Begin documenting colonial realities.', requirement: { type: 'action', target: 'mexico_political' }, text: 'The contradictions of empire are everywhere. Liberty proclaimed, bondage practiced.', completed: false },
      { id: 'col_2', title: 'The Mine\'s Truth', description: 'Document the human cost of silver.', requirement: { type: 'action', target: 'mexico_mine' }, text: 'The Valenciana mine reveals everything — wealth built on suffering, progress measured in lives.', completed: false, reward: { flag: 'colonial_documented' } },
    ],
  },
  {
    id: 'kosmos', title: 'Kosmos', icon: '✦',
    description: 'Write your masterwork unifying all of nature.',
    currentStage: 0,
    stages: [
      { id: 'kos_1', title: 'The Great Work', description: 'Complete Kosmos.', requirement: { type: 'flag', target: 'kosmos_written' }, text: 'Kosmos is complete. You have unified all knowledge into a single vision of nature as a living whole.', completed: false },
    ],
  },
];

// ===== RELATIONSHIPS =====
export const initialRelationships: Relationship[] = [
  { id: 'bonpland', name: 'Aimé Bonpland', title: 'Companion & Botanist', value: 0, icon: '🌱', description: 'Your partner in exploration. French botanist of extraordinary skill.' },
  { id: 'indigenous', name: 'Indigenous Guides', title: 'Keepers of the Land', value: 0, icon: '🪶', description: 'The peoples who have lived with this land for millennia.' },
  { id: 'scientific_community', name: 'Scientific Community', title: 'Your Peers', value: 0, icon: '🔬', description: 'Fellow scientists across Europe and beyond.' },
  { id: 'goethe', name: 'Johann W. von Goethe', title: 'Poet & Scientist', value: 0, icon: '🪶', description: 'The great writer who taught you to merge art and science.' },
  { id: 'herz', name: 'Henriette Herz', title: 'Salon Hostess', value: 0, icon: '💫', description: 'Intellectual leader of Berlin\'s salon culture.' },
];

// ===== RANDOM EVENTS =====
export const randomEvents: RandomEvent[] = [
  { id: 'fever', title: 'Tropical Fever', text: 'A sudden fever strikes. You spend days shivering in a hammock, unable to work.', probability: 0.15, minCycle: 3, effects: { vitality: -15, supplies: -5 }, once: true },
  { id: 'storm', title: 'Violent Storm', text: 'A tropical storm batters the expedition. Equipment is damaged, supplies scattered.', probability: 0.12, minCycle: 2, effects: { instruments: -8, supplies: -8 }, once: true },
  { id: 'discovery', title: 'Unexpected Discovery', text: 'While resting, you notice a remarkable specimen you had overlooked. Nature rewards the patient observer.', probability: 0.15, minCycle: 4, effects: { data: 8 } },
  { id: 'supply_cache', title: 'Supply Cache Found', text: 'A previously cached supply depot is found intact. A stroke of luck.', probability: 0.1, minCycle: 5, effects: { supplies: 15 } },
  { id: 'instrument_damage', title: 'Instrument Malfunction', text: 'Your barometer cracks during transport. Precise measurements become more difficult.', probability: 0.1, minCycle: 3, effects: { instruments: -10 } },
  { id: 'kind_stranger', title: 'A Kind Stranger', text: 'A local family offers food and shelter. Their generosity restores your faith in humanity.', probability: 0.12, minCycle: 2, effects: { supplies: 8, vitality: 5 } },
  { id: 'journal_theft', title: 'Notes Damaged', text: 'Humidity has damaged some of your field notes. Irreplaceable observations lost.', probability: 0.08, minCycle: 6, effects: { data: -5 } },
  { id: 'funding', title: 'Royal Funding Arrives', text: 'A shipment of credits from the Crown arrives, along with a letter of encouragement.', probability: 0.1, minCycle: 8, effects: { credits: 20 } },
  { id: 'bonpland_ill', title: 'Bonpland Falls Ill', text: 'Your companion is struck by illness. You must care for him, losing time but gaining closeness.', probability: 0.1, minCycle: 4, effects: { vitality: -5 }, flag: 'cared_for_bonpland', once: true },
  { id: 'moment_of_wonder', title: 'Moment of Wonder', text: 'A sunset of impossible color. A bird of paradise. A flower that glows. Nature reminds you why you began this journey.', probability: 0.2, minCycle: 1, effects: { vitality: 5, data: 2 } },
];

// ===== NATURGEMLÄLDE NODES =====
export const naturgemaldeNodes: NaturgemaldeNode[] = [
  { id: 'tropical_flora', label: 'Tropical Flora', category: 'flora', x: 50, y: 88, connections: ['subtropical_flora', 'insects'], discovered: false },
  { id: 'subtropical_flora', label: 'Subtropical Forest', category: 'flora', x: 35, y: 72, connections: ['temperate_flora', 'tropical_flora'], discovered: false },
  { id: 'temperate_flora', label: 'Temperate Oaks', category: 'flora', x: 42, y: 56, connections: ['alpine_moss', 'subtropical_flora'], discovered: false },
  { id: 'alpine_moss', label: 'Alpine Vegetation', category: 'flora', x: 55, y: 42, connections: ['snow_line', 'temperate_flora'], discovered: false },
  { id: 'snow_line', label: 'Permanent Snow', category: 'climate', x: 50, y: 22, connections: ['alpine_moss', 'atmosphere'], discovered: false },
  { id: 'atmosphere', label: 'Atmospheric Pressure', category: 'climate', x: 78, y: 28, connections: ['snow_line', 'temperature'], discovered: false },
  { id: 'temperature', label: 'Temperature Gradient', category: 'climate', x: 82, y: 52, connections: ['atmosphere', 'geology'], discovered: false },
  { id: 'geology', label: 'Volcanic Geology', category: 'geology', x: 22, y: 48, connections: ['temperature', 'minerals'], discovered: false },
  { id: 'minerals', label: 'Mineral Deposits', category: 'geology', x: 18, y: 72, connections: ['geology', 'insects'], discovered: false },
  { id: 'insects', label: 'Insect Life', category: 'fauna', x: 65, y: 82, connections: ['tropical_flora', 'condors'], discovered: false },
  { id: 'condors', label: 'Andean Condors', category: 'fauna', x: 70, y: 38, connections: ['snow_line', 'insects'], discovered: false },
  { id: 'indigenous', label: 'Indigenous Knowledge', category: 'culture', x: 30, y: 85, connections: ['tropical_flora', 'minerals'], discovered: false },
  { id: 'measurement', label: 'Barometric Data', category: 'measurement', x: 85, y: 70, connections: ['temperature', 'geology'], discovered: false },
];
